/**
 * Centralized validation code identifiers to ensure consistency across modules.
 */
export const Codes = {
    // Ticker info
    TICKER_MODIFY: 'PSV6-TICKER-MODIFY',
    TICKER_SETTLEMENT_INFO: 'PSV6-TICKER-SETTLEMENT',
    TICKER_RENKO_INFO: 'PSV6-TICKER-RENKO',
    TICKER_PNF_INFO: 'PSV6-TICKER-PNF',
    TICKER_KAGI_INFO: 'PSV6-TICKER-KAGI',
    TICKER_HEIKIN_INFO: 'PSV6-TICKER-HEIKIN',
    TICKER_INHERIT_INFO: 'PSV6-TICKER-INHERIT',
    TICKER_NEW_INFO: 'PSV6-TICKER-NEW',
    // Ticker errors
    TICKER_MODIFY_UNKNOWN_PARAM: 'PSV6-TICKER-MODIFY-UNKNOWN-PARAM',
    TICKER_SETTLEMENT_VALUE: 'PSV6-TICKER-SETTLEMENT-VALUE',
    TICKER_ADJ_VALUE: 'PSV6-TICKER-ADJ-VALUE',
    TICKER_BACKADJ_VALUE: 'PSV6-TICKER-BACKADJ-VALUE',
    TICKER_SESSION_VALUE: 'PSV6-TICKER-SESSION-VALUE',
    TICKER_RENKO_SIZETYPE: 'PSV6-TICKER-RENKO-SIZETYPE',
    TICKER_RENKO_SIZE_TYPE: 'PSV6-TICKER-RENKO-SIZE-TYPE',
    TICKER_RENKO_WICKS_TYPE: 'PSV6-TICKER-RENKO-WICKS-TYPE',
    TICKER_RENKO_SOURCE: 'PSV6-TICKER-RENKO-SOURCE',
    TICKER_PNF_SOURCE: 'PSV6-TICKER-PNF-SOURCE',
    TICKER_PNF_SIZE_TYPE: 'PSV6-TICKER-PNF-SIZE-TYPE',
    TICKER_PNF_BOXSIZE: 'PSV6-TICKER-PNF-BOXSIZE',
    TICKER_PNF_REVERSAL_TYPE: 'PSV6-TICKER-PNF-REVERSAL-TYPE',
    TICKER_KAGI_PARAM_TYPE: 'PSV6-TICKER-KAGI-PARAM-TYPE',
    TICKER_KAGI_STYLE: 'PSV6-TICKER-KAGI-STYLE',
    // Generic categories (shared)
    SPECIALIZED_CONSTANT: 'PSV6-SPECIALIZED-CONSTANT',
    // Builtins/constants common codes
    DISPLAY_CONSTANT: 'PSV6-DISPLAY-CONSTANT',
    TIMEFRAME_CONSTANT: 'PSV6-TIMEFRAME-CONSTANT',
    EXTEND_CONSTANT: 'PSV6-EXTEND-CONSTANT',
    FORMAT_CONSTANT: 'PSV6-FORMAT-CONSTANT',
    CURRENCY_CONSTANT: 'PSV6-CURRENCY-CONSTANT',
    SCALE_CONSTANT: 'PSV6-SCALE-CONSTANT',
    ADJUSTMENT_CONSTANT: 'PSV6-ADJUSTMENT-CONSTANT',
    BACKADJUSTMENT_CONSTANT: 'PSV6-BACKADJUSTMENT-CONSTANT',
    BUILTIN_VARS_INFO: 'PSV6-BUILTIN-VARS-INFO',
    CURRENCY_USAGE: 'PSV6-CURRENCY-USAGE',
    DISPLAY_USAGE: 'PSV6-DISPLAY-USAGE',
    SCALE_USAGE: 'PSV6-SCALE-USAGE',
    ADJUSTMENT_USAGE: 'PSV6-ADJUSTMENT-USAGE',
    // Final constants
    STYLE_CONSTANT: 'PSV6-STYLE-CONSTANT',
    ORDER_CONSTANT: 'PSV6-ORDER-CONSTANT',
    POSITION_CONSTANT: 'PSV6-POSITION-CONSTANT',
    FINAL_CONSTANTS_INFO: 'PSV6-FINAL-CONSTANTS-INFO',
    MATH_CONSTANTS_USAGE: 'PSV6-MATH-CONSTANTS-USAGE',
    // Additional constants and syminfo
    ADDITIONAL_CONSTANT: 'PSV6-ADDITIONAL-CONSTANT',
    SYMINFO_ADDITIONAL: 'PSV6-SYMINFO-ADDITIONAL',
    // Strategy function codes
    STRATEGY_FUNCTION_PARAM: 'PSV6-STRATEGY-FUNCTION-PARAM',
    STRATEGY_FUNCTION_UNKNOWN: 'PSV6-STRATEGY-FUNCTION-UNKNOWN',
    STRATEGY_INVALID: 'PSV6-STRATEGY-INVALID',
    STRATEGY_CONSTANT_AS_FUNCTION: 'PSV6-STRATEGY-CONSTANT-AS-FUNCTION',
    STRATEGY_ALLOW_ENTRY_PARAMS: 'PSV6-STRATEGY-ALLOW-ENTRY-PARAMS',
    STRATEGY_MAX_POSITION_SIZE: 'PSV6-STRATEGY-MAX-POSITION-SIZE',
    STRATEGY_MAX_DRAWDOWN_VALUE: 'PSV6-STRATEGY-MAX-DRAWDOWN-VALUE',
    STRATEGY_MAX_ORDERS_VALUE: 'PSV6-STRATEGY-MAX-ORDERS-VALUE',
    // Core syntax codes
    NUMERIC_CONDITION: 'PSV6-001',
    MIXED_INDENTATION: 'PSV6-STYLE-MIXED-INDENTATION',
    PERFORMANCE_ALERT_CONSOLIDATE: 'PSV6-PERF-ALERT-CONSOLIDATE',
    TERNARY_TYPE: 'PSV6-TERNARY-TYPE',
    TYPE_FLOW: 'PSV6-TYPE-FLOW',
    FUNCTION_NAMESPACE: 'PSV6-FUNCTION-NAMESPACE',
    // Legacy codes for compatibility
    INVALID_OPERATOR: 'PSO01',
    ASSIGNMENT_IN_CONDITION: 'PSO02',
    MIXED_TABS_SPACES: 'PSI02',
    CURLY_BRACES: 'PS011'
};
