// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: 2025-10-03T21:07:53.686Z

export * from './variables';
export * from './functions';
export * from './constants';
export * from './keywords';
export * from './operators';
export * from './types';
export * from './annotations';

import { variables } from './variables';
import { functions } from './functions';
import { constants } from './constants';
import { keywords } from './keywords';
import { operators } from './operators';
import { types } from './types';
import { annotations } from './annotations';

export const pineScriptDocumentation = {
  variables,
  functions,
  constants,
  keywords,
  operators,
  types,
  annotations,
} as const;

export type PineScriptDocumentation = typeof pineScriptDocumentation;
