// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: 2025-10-03T21:07:53.685Z

export interface PineKeywordMetadata {
  readonly name: string;
  readonly description: string;
  readonly syntax?: string;
  readonly example?: string;
  readonly remarks?: string;
  readonly returns?: string;
  readonly seeAlso?: ReadonlyArray<{ name: string; reference: string }>;
}

export const keywords: Record<string, PineKeywordMetadata> = {
  "and": {
    "name": "and",
    "description": "Logical AND. Applicable to boolean expressions.",
    "syntax": "expr1 and expr2",
    "remarks": "If expr1 evaluates to false, the and operator returns false without evaluating expr2.",
    "returns": "Boolean value, or series of boolean values."
  },
  "enum": {
    "name": "enum",
    "description": "This keyword allows the creation of an enumeration, enum for short. Enums are unique constructs that hold groups of predefined constants.",
    "syntax": "[export ]enum <enumName> \n<field_1> [= <title_1>] \n<field_2> [= <title_2>] \n... \n<field_N> [= <title_N>]",
    "example": "//@version=6indicator(\"Map with enum keys\")//@enum        Contains fields with titles representing ticker IDs.//@field aapl  Has an Apple ticker ID as its title.//@field tsla  Has a Tesla ticker ID as its title.//@field amzn  Has an Amazon ticker ID as its title.enum symbols    aapl = \"NASDAQ:AAPL\"    tsla = \"NASDAQ:TSLA\"    amzn = \"NASDAQ:AMZN\"//@variable A map that accepts fields from the `symbols` enum as keys and \"float\" values.map<symbols, float> data = map.new<symbols, float>()// Put key-value pairs into the `data` map.data.put(symbols.aapl, request.security(str.tostring(symbols.aapl), timeframe.period, close))data.put(symbols.tsla, request.security(str.tostring(symbols.tsla), timeframe.period, close))data.put(symbols.amzn, request.security(str.tostring(symbols.amzn), timeframe.period, close))// Plot the value from the `data` map accessed by the `symbols.aapl` key.plot(data.get(symbols.aapl))"
  },
  "export": {
    "name": "export",
    "description": "Used in libraries to prefix the declaration of functions or user-defined type definitions that will be available from other scripts importing the library.",
    "example": "//@version=6//@description Library of debugging functions.library(\"Debugging_library\", overlay = true)//@function Displays a string as a table cell for debugging purposes.//@param txt String to display.//@returns Void.export print(string txt) =>    var table t = table.new(position.middle_right, 1, 1)    table.cell(t, 0, 0, txt, bgcolor = color.yellow)// Using the function from inside the library to show an example on the published chart.// This has no impact on scripts using the library.print(\"Library Test\")",
    "remarks": "Each library must have at least one exported function or user-defined type (UDT).",
    "seeAlso": [
      {
        "name": "library",
        "reference": "fun_library"
      },
      {
        "name": "import",
        "reference": "kw_import"
      },
      {
        "name": "simple",
        "reference": "type_simple"
      },
      {
        "name": "series",
        "reference": "type_series"
      },
      {
        "name": "type",
        "reference": "kw_type"
      }
    ]
  },
  "for": {
    "name": "for",
    "description": "Creates a count-controlled loop, which uses a counter variable to manage the iterative executions of its local code block. The loop continues new iterations until the counter reaches a specified final value.",
    "syntax": "[variables =|:=] for counter = from_num to to_num [by step_num]\n    statements | continue | break\n    return_expression",
    "example": "//@version=6indicator(\"`for` loop with a step\")a = array.from(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)sum = 0.0for i = 0 to 9 by 5    // Because the step is set to 5, we are adding only the first (0) and the sixth (5) value from the array `a`.    sum += array.get(a, i)plot(sum)",
    "remarks": "Modifying a loop's to_num value during an iteration does not change the direction of the loop's counter. For a loop that counts upward, setting the to_num to a value less than the from_num value on an iteration stops the loop immediately after that iteration ends. Likewise, a loop that counts downward stops after an iteration where the to_num value becomes greater than the from_num value.",
    "seeAlso": [
      {
        "name": "for...in",
        "reference": "kw_for...in"
      },
      {
        "name": "while",
        "reference": "kw_while"
      }
    ]
  },
  "for...in": {
    "name": "for...in",
    "description": "The for...in structure allows the repeated execution of a number of statements for each element in an array. It can be used with either one argument: array_element, or with two: [index, array_element]. The second form doesn't affect the functionality of the loop. It tracks the current iteration's index in the tuple's first variable.",
    "syntax": "[var_declaration =] for array_element in array_id\n    statements | continue | break\n    return_expression\n\n[var_declaration =] for [index, array_element] in array_id\n    statements | continue | break\n    return_expression",
    "example": "//@version=6indicator(\"`for ... in` matrix Example\")// Create a 2x3 matrix with values `4`.matrix1 = matrix.new<int>(2, 3, 4)sum = 0.0// Loop through every row of the matrix.for rowArray in matrix1    // Sum values of the every row    sum += array.sum(rowArray)plot(sum)",
    "seeAlso": [
      {
        "name": "for",
        "reference": "kw_for"
      },
      {
        "name": "while",
        "reference": "kw_while"
      },
      {
        "name": "array.sum",
        "reference": "fun_array.sum"
      },
      {
        "name": "array.min",
        "reference": "fun_array.min"
      },
      {
        "name": "array.max",
        "reference": "fun_array.max"
      }
    ]
  },
  "if": {
    "name": "if",
    "description": "If statement defines what block of statements must be executed when conditions of the expression are satisfied.",
    "syntax": "var_declarationX = if condition\n    var_decl_then0\n    var_decl_then1\n    …\n    var_decl_thenN\nelse if [optional block]\n    var_decl_else0\n    var_decl_else1\n    …\n    var_decl_elseN\nelse\n    var_decl_else0\n    var_decl_else1\n    …\n    var_decl_elseN\n    return_expression_else",
    "example": "//@version=6indicator(\"if\")float x = naif close > open    if close > close[1]        x := close    else        x := close[1]else    x := openplot(x)"
  },
  "import": {
    "name": "import",
    "description": "Used to load an external library into a script and bind its functions to a namespace. The importing script can be an indicator, a strategy, or another library. A library must be published (privately or publicly) before it can be imported.",
    "syntax": "import {username}/{libraryName}/{libraryVersion} as {alias}",
    "example": "//@version=6indicator(\"num_methods import\")// Import the first version of the username’s \"num_methods\" library and assign it to the \"m\" namespace\",import username/num_methods/1 as m// Call the “sinh()” function from the imported libraryy = m.sinh(3.14)// Plot value returned by the \"sinh()\" function\",plot(y)",
    "remarks": "Using an alias that replaces a built-in namespace such as math.* or strategy.* is allowed, but if the library contains function names that shadow Pine Script®'s built-in functions, the built-ins will become unavailable. The same version of a library can only be imported once. Aliases must be distinct for each imported library. When calling library functions, casting their arguments to types other than their declared type is not allowed. An import statement cannot use 'as' or 'import' as username, libraryName, or alias identifiers.",
    "seeAlso": [
      {
        "name": "library",
        "reference": "fun_library"
      },
      {
        "name": "export",
        "reference": "kw_export"
      }
    ]
  },
  "method": {
    "name": "method",
    "description": "This keyword is used to prefix a function declaration, indicating it can then be invoked using dot notation by appending its name to a variable of the type of its first parameter and omitting that first parameter. Alternatively, functions declared as methods can also be invoked like normal user-defined functions. In that case, an argument must be supplied for its first parameter.",
    "syntax": "[export] method <functionName>(<paramType> <paramName> [= <defaultValue>], …) =>\n    <functionBlock>",
    "example": "//@version=6indicator(\"\")var prices = array.new<float>()//@function Pushes a new value into the array and removes the first one if the resulting array is greater than `maxSize`. Can be used as a method.method maintainArray(array<float> id, maxSize, value) =>    id.push(value)    if id.size() > maxSize        id.shift()prices.maintainArray(50, close)// The method can also be called like a function, without using dot notation.// In this case an argument must be supplied for its first parameter.// maintainArray(prices, 50, close)// This calls the `array.avg()` built-in using dot notation with the `prices` array.// It is possible because built-in functions belonging to some namespaces that are a special Pine type// can be invoked with method notation when the function's first parameter is an ID of that type.// Those namespaces are: `array`, `matrix`, `line`, `linefill`, `label`, `box`, and `table`.plot(prices.avg())"
  },
  "not": {
    "name": "not",
    "description": "Logical negation (NOT). Applicable to boolean expressions.",
    "syntax": "not expr1",
    "returns": "Boolean value, or series of boolean values."
  },
  "or": {
    "name": "or",
    "description": "Logical OR. Applicable to boolean expressions.",
    "syntax": "expr1 or expr2",
    "remarks": "If expr1 evaluates to true, the or operator returns true without evaluating expr2.",
    "returns": "Boolean value, or series of boolean values."
  },
  "switch": {
    "name": "switch",
    "description": "The switch operator transfers control to one of the several statements, depending on the values of a condition and expressions.",
    "syntax": "[variable_declaration = ] switch expression\n    value1 => local_block\n    value2 => local_block\n    …\n    => default_local_block\n\n[variable_declaration = ] switch\n    condition1 => local_block\n    condition2 => local_block\n    …\n    => default_local_block",
    "example": "//@version=6strategy(\"Switch without an expression\", overlay = true)bool longCondition  = ta.crossover( ta.sma(close, 14), ta.sma(close, 28))bool shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))switch    longCondition  => strategy.entry(\"Long ID\", strategy.long)    shortCondition => strategy.entry(\"Short ID\", strategy.short)",
    "remarks": "Only one of the local_block instances or the default_local_block can be executed. The default_local_block is introduced with the => token alone and is only executed when none of the preceding blocks are executed. If the result of the switch statement is assigned to a variable and a default_local_block is not specified, the statement returns na if no local_block is executed. When assigning the result of the switch statement to a variable, all local_block instances must return the same type of value.",
    "returns": "The value of the last expression in the local block of statements that is executed.",
    "seeAlso": [
      {
        "name": "if",
        "reference": "kw_if"
      },
      {
        "name": "?:",
        "reference": "op_?:"
      }
    ]
  },
  "type": {
    "name": "type",
    "description": "This keyword allows the declaration of user-defined types (UDT) from which scripts can instantiate objects. UDTs are composite types that contain an arbitrary number of fields of any built-in or user-defined type, including the defined UDT itself. The syntax to define a UDT is:",
    "syntax": "[export ]type <UDT_identifier>\n    [varip ]<field_type> <field_name> [= <value>]\n    …",
    "example": "//@version=6indicator(\"Multi Time Period Chart\", overlay = true)timeframeInput = input.timeframe(\"1D\")type bar    float o = open    float h = high    float l = low    float c = close    int   t = timedrawBox(bar b, right) =>    color boxColor = b.c >= b.o ? color.green : color.red    box.new(b.t, b.h, right, b.l, boxColor, xloc = xloc.bar_time, bgcolor = color.new(boxColor, 90))updateBox(box boxId, bar b) =>    color boxColor = b.c >= b.o ? color.green : color.red    box.set_border_color(boxId, boxColor)    box.set_bgcolor(boxId, color.new(boxColor, 90))    box.set_top(boxId, b.h)    box.set_bottom(boxId, b.l)    box.set_right(boxId, time)secBar = request.security(syminfo.tickerid, timeframeInput, bar.new())if not na(secBar)    // To avoid a runtime error, only process data when an object exists.    if not barstate.islast        if timeframe.change(timeframeInput)            // On historical bars, draw a new box in the past when the HTF closes.            drawBox(secBar, time[1])    else        var box lastBox = na        if na(lastBox) or timeframe.change(timeframeInput)            // On the last bar, only draw a new current box the first time we get there or when HTF changes.            lastBox := drawBox(secBar, time)        else            // On other chart updates, use setters to modify the current box.            updateBox(lastBox, secBar)"
  },
  "var": {
    "name": "var",
    "description": "var is the keyword used for assigning and one-time initializing of the variable.",
    "syntax": "var variable_name = expression",
    "example": "//@version=6indicator(\"Var keyword example\")var a = closevar b = 0.0var c = 0.0var green_bars_count = 0if close > open    var x = close    b := x    green_bars_count := green_bars_count + 1    if green_bars_count >= 10        var y = close        c := yplot(a)plot(b)plot(c)"
  },
  "varip": {
    "name": "varip",
    "description": "varip (var intrabar persist) is the keyword used for the assignment and one-time initialization of a variable or a field of a user-defined type. It’s similar to the var keyword, but variables and fields declared with varip retain their values between executions of the script on the same bar.",
    "syntax": "varip [<variable_type> ]<variable_name> = <expression>\n\n[export ]type <UDT_identifier>\n    varip <field_type> <field_name> [= <value>]",
    "example": "//@version=6indicator(\"varip with types\")type barData    int index = -1    varip int ticks = -1var currBar = barData.new()currBar.index += 1currBar.ticks += 1// Will be equal to bar_index on all barsplot(currBar.index)// In real time, will increment per every tick on the chartplot(currBar.ticks)",
    "remarks": "When using varip to declare variables in strategies that may execute more than once per historical chart bar, the values of such variables are preserved across successive iterations of the script on the same bar."
  },
  "while": {
    "name": "while",
    "description": "The while statement allows the conditional iteration of a local code block.",
    "syntax": "variable_declaration = while condition\n    …\n    continue\n    …\n    break\n    …\n    return_expression",
    "example": "//@version=6indicator(\"while\")// This is a simple example of calculating a factorial using a while loop.int i_n = input.int(10, \"Factorial Size\", minval=0)int counter   = i_nint factorial = 1while counter > 0    factorial := factorial * counter    counter   := counter - 1plot(factorial)",
    "remarks": "The local code block after the initial while line must be indented with four spaces or a tab. For the while loop to terminate, the boolean expression following while must eventually become false, or a break must be executed."
  }
} as const;
