// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: 2025-10-03T21:07:53.685Z

export interface PineTypeMetadata {
  readonly name: string;
  readonly description: string;
  readonly fields?: string;
  readonly example?: string;
  readonly remarks?: string;
  readonly seeAlso?: ReadonlyArray<{ name: string; reference: string }>;
}

export const types: Record<string, PineTypeMetadata> = {
  "array": {
    "name": "array",
    "description": "Keyword used to explicitly declare the \"array\" type of a variable or a parameter. Array objects (or IDs) can be created with the array.new<type>, array.from function.",
    "example": "//@version=6indicator(\"array\", overlay=true)array<float> a = naa := array.new<float>(1, close)plot(array.get(a, 0))",
    "remarks": "Array objects are always of \"series\" form.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "line",
        "reference": "type_line"
      },
      {
        "name": "label",
        "reference": "type_label"
      },
      {
        "name": "table",
        "reference": "type_table"
      },
      {
        "name": "box",
        "reference": "type_box"
      },
      {
        "name": "array.new<type>",
        "reference": "fun_array.new<type>"
      },
      {
        "name": "array.from",
        "reference": "fun_array.from"
      }
    ]
  },
  "bool": {
    "name": "bool",
    "description": "Keyword used to explicitly declare the \"bool\" (boolean) type of a variable or a parameter. \"Bool\" variables can have values true or false.",
    "example": "//@version=6indicator(\"bool\")bool b = true    // Same as `b = true`plot(b ? open : close)",
    "remarks": "Explicitly mentioning the type in a variable declaration is optional. Learn more about Pine Script® types in the User Manual page on the Type System.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "varip",
        "reference": "kw_varip"
      },
      {
        "name": "int",
        "reference": "type_int"
      },
      {
        "name": "float",
        "reference": "type_float"
      },
      {
        "name": "color",
        "reference": "type_color"
      },
      {
        "name": "string",
        "reference": "type_string"
      },
      {
        "name": "true",
        "reference": "const_true"
      },
      {
        "name": "false",
        "reference": "const_false"
      }
    ]
  },
  "box": {
    "name": "box",
    "description": "Keyword used to explicitly declare the \"box\" type of a variable or a parameter. Box objects (or IDs) can be created with the box.new function.",
    "example": "//@version=6indicator(\"box\")// Empty `box1` box ID.var box box1 = na// `box` type is unnecessary because `box.new()` returns a \"box\" type.var box2 = box.new(na, na, na, na)box3 = box.new(time, open, time + 60 * 60 * 24, close, xloc=xloc.bar_time)",
    "remarks": "Box objects are always of \"series\" form.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "line",
        "reference": "type_line"
      },
      {
        "name": "label",
        "reference": "type_label"
      },
      {
        "name": "table",
        "reference": "type_table"
      },
      {
        "name": "box.new",
        "reference": "fun_box.new"
      }
    ]
  },
  "chart.point": {
    "name": "chart.point",
    "description": "Keyword to explicitly declare the type of a variable or parameter as chart.point. Scripts can produce chart.point instances using the chart.point.from_time, chart.point.from_index, chart.point.now, and chart.point.new functions.",
    "fields": "index (series int) The x-coordinate of the point, expressed as a bar index value.",
    "seeAlso": [
      {
        "name": "polyline",
        "reference": "type_polyline"
      }
    ]
  },
  "color": {
    "name": "color",
    "description": "Keyword used to explicitly declare the \"color\" type of a variable or a parameter.",
    "example": "//@version=6indicator(\"color\", overlay = true)color textColor = color.greencolor labelColor = #FF000080 // Red color (FF0000) with 50% transparency (80 which is half of FF).if barstate.islastconfirmedhistory    label.new(bar_index, high, text = \"Label\", color = labelColor, textcolor = textColor)// When declaring variables with color literals, built-in constants(color.green) or functions (color.new(), color.rgb()), the \"color\" keyword for the type can be omitted.c = color.rgb(0,255,0,0)plot(close, color = c)",
    "remarks": "Color literals have the following format: #RRGGBB or #RRGGBBAA. The letter pairs represent 00 to FF hexadecimal values (0 to 255 in decimal) where RR, GG and BB pairs are the values for the color's red, green and blue components. AA is an optional value for the color's transparency (or alpha component) where 00 is invisible and FF opaque. When no AA pair is supplied, FF is used. The hexadecimal letters can be upper or lower case.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "varip",
        "reference": "kw_varip"
      },
      {
        "name": "int",
        "reference": "type_int"
      },
      {
        "name": "float",
        "reference": "type_float"
      },
      {
        "name": "string",
        "reference": "type_string"
      },
      {
        "name": "color.rgb",
        "reference": "fun_color.rgb"
      },
      {
        "name": "color.new",
        "reference": "fun_color.new"
      }
    ]
  },
  "const": {
    "name": "const",
    "description": "The const keyword explicitly assigns the \"const\" type qualifier to variables and the parameters of non-exported functions. Variables and parameters with the \"const\" qualifier reference values established at compile time that never change in the script's execution.",
    "example": "//@version=6indicator(\"can't assign input to const\")//@variable A variable declared as \"const float\" that attempts to assign the result of `input.float()` as its value.//          This declaration causes an error. The \"input float\" qualified type is stronger than \"const float\".const float myVar = input.float(2.0)plot(myVar)",
    "remarks": "To learn more, see our User Manual's section on type qualifiers.",
    "seeAlso": [
      {
        "name": "simple",
        "reference": "type_simple"
      },
      {
        "name": "series",
        "reference": "type_series"
      }
    ]
  },
  "float": {
    "name": "float",
    "description": "Keyword used to explicitly declare the \"float\" (floating point) type of a variable or a parameter.",
    "example": "//@version=6indicator(\"float\")float f = 3.14    // Same as `f = 3.14`f := naplot(f)",
    "remarks": "Explicitly mentioning the type in a variable declaration is optional, except when it is initialized with na. Learn more about Pine Script® types in the User Manual page on the Type System.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "varip",
        "reference": "kw_varip"
      },
      {
        "name": "int",
        "reference": "type_int"
      },
      {
        "name": "bool",
        "reference": "type_bool"
      },
      {
        "name": "color",
        "reference": "type_color"
      },
      {
        "name": "string",
        "reference": "type_string"
      }
    ]
  },
  "int": {
    "name": "int",
    "description": "Keyword used to explicitly declare the \"int\" (integer) type of a variable or a parameter.",
    "example": "//@version=6indicator(\"int\")int i = 14    // Same as `i = 14`i := naplot(i)",
    "remarks": "Explicitly mentioning the type in a variable declaration is optional, except when it is initialized with na. Learn more about Pine Script® types in the User Manual page on the Type System.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "varip",
        "reference": "kw_varip"
      },
      {
        "name": "float",
        "reference": "type_float"
      },
      {
        "name": "bool",
        "reference": "type_bool"
      },
      {
        "name": "color",
        "reference": "type_color"
      },
      {
        "name": "string",
        "reference": "type_string"
      }
    ]
  },
  "label": {
    "name": "label",
    "description": "Keyword used to explicitly declare the \"label\" type of a variable or a parameter. Label objects (or IDs) can be created with the label.new function.",
    "example": "//@version=6indicator(\"label\")// Empty `label1` label ID.var label label1 = na// `label` type is unnecessary because `label.new()` returns \"label\" type.var label2 = label.new(na, na, na)if barstate.islastconfirmedhistory    label3 = label.new(bar_index, high, text = \"label3 text\")",
    "remarks": "Label objects are always of \"series\" form.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "line",
        "reference": "type_line"
      },
      {
        "name": "box",
        "reference": "type_box"
      },
      {
        "name": "label.new",
        "reference": "fun_label.new"
      }
    ]
  },
  "line": {
    "name": "line",
    "description": "Keyword used to explicitly declare the \"line\" type of a variable or a parameter. Line objects (or IDs) can be created with the line.new function.",
    "example": "//@version=6indicator(\"line\")// Empty `line1` line ID.var line line1 = na// `line` type is unnecessary because `line.new()` returns \"line\" type.var line2 = line.new(na, na, na, na)line3 = line.new(bar_index - 1, high, bar_index, high, extend = extend.right)",
    "remarks": "Line objects are always of \"series\" form.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "label",
        "reference": "type_label"
      },
      {
        "name": "box",
        "reference": "type_box"
      },
      {
        "name": "line.new",
        "reference": "fun_line.new"
      }
    ]
  },
  "linefill": {
    "name": "linefill",
    "description": "Keyword used to explicitly declare the \"linefill\" type of a variable or a parameter. Linefill objects (or IDs) can be created with the linefill.new function.",
    "example": "//@version=6indicator(\"linefill\", overlay=true)// Empty `linefill1` line ID.var linefill linefill1 = na// `linefill` type is unnecessary because `linefill.new()` returns \"linefill\" type.var linefill2 = linefill.new(na, na, na)if barstate.islastconfirmedhistory    line1 = line.new(bar_index - 10, high+1, bar_index, high+1, extend = extend.right)    line2 = line.new(bar_index - 10, low+1, bar_index, low+1, extend = extend.right)    linefill3 = linefill.new(line1, line2, color = color.new(color.green, 80))",
    "remarks": "Linefill objects are always of \"series\" form.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "line",
        "reference": "type_line"
      },
      {
        "name": "label",
        "reference": "type_label"
      },
      {
        "name": "table",
        "reference": "type_table"
      },
      {
        "name": "box",
        "reference": "type_box"
      },
      {
        "name": "linefill.new",
        "reference": "fun_linefill.new"
      }
    ]
  },
  "map": {
    "name": "map",
    "description": "Keyword used to explicitly declare the \"map\" type of a variable or a parameter. Map objects (or IDs) can be created with the map.new<type,type> function.",
    "example": "//@version=6indicator(\"map\", overlay=true)map<int, float> a = naa := map.new<int, float>()a.put(bar_index, close)label.new(bar_index, a.get(bar_index), \"Current close\")",
    "remarks": "Map objects are always of series form.",
    "seeAlso": [
      {
        "name": "map.new<type,type>",
        "reference": "fun_map.new<type,type>"
      }
    ]
  },
  "matrix": {
    "name": "matrix",
    "description": "Keyword used to explicitly declare the \"matrix\" type of a variable or a parameter. Matrix objects (or IDs) can be created with the matrix.new<type> function.",
    "example": "//@version=6indicator(\"matrix example\")// Create `m1` matrix of `int` type.matrix<int> m1 = matrix.new<int>(2, 3, 0)// `matrix<int>` is unnecessary because the `matrix.new<int>()` function returns an `int` type matrix object.m2 = matrix.new<int>(2, 3, 0)// Display matrix using a label.if barstate.islastconfirmedhistory    label.new(bar_index, high, str.tostring(m2))",
    "remarks": "Matrix objects are always of \"series\" form.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "matrix.new<type>",
        "reference": "fun_matrix.new<type>"
      },
      {
        "name": "array",
        "reference": "type_array"
      }
    ]
  },
  "polyline": {
    "name": "polyline",
    "description": "Keyword to explicitly declare the type of a variable or parameter as polyline. Scripts can produce polyline instances using the polyline.new function.",
    "seeAlso": [
      {
        "name": "chart.point",
        "reference": "type_chart.point"
      }
    ]
  },
  "series": {
    "name": "series",
    "description": "The series keyword explicitly assigns the \"series\" type qualifier to variables and function parameters. Variables and parameters that use the \"series\" qualifier can reference values that change throughout a script's execution.",
    "example": "//@version=6indicator(\"series variable not allowed\")//@variable A variable declared as \"series int\" with a value of 5.series int myVar = 5// This call causes an error.// The `histbase` accepts \"input int/float\". It can't accept the stronger \"series int\" qualified type.plot(close, style = plot.style_histogram, histbase = myVar)",
    "remarks": "To learn more, see our User Manual's section on type qualifiers.",
    "seeAlso": [
      {
        "name": "simple",
        "reference": "type_simple"
      },
      {
        "name": "const",
        "reference": "type_const"
      }
    ]
  },
  "simple": {
    "name": "simple",
    "description": "The simple keyword explicitly assigns the \"simple\" type qualifier to variables and function parameters. Variables and parameters that use the \"simple\" qualifier can reference values established at the beginning of a script's execution that do not change later.",
    "example": "//@version=6indicator(\"can't change simple to series\")//@variable A variable declared as \"simple float\" with a value of 5.0.simple float myVar = 5.0// This reassignment causes an error.// The `close` variable returns a \"series float\" value. Since `myVar` is restricted to \"simple\" values, it cannot// change its qualifier to \"series\".myVar := closeplot(myVar)",
    "remarks": "To learn more, see our User Manual's section on type qualifiers.",
    "seeAlso": [
      {
        "name": "series",
        "reference": "type_series"
      },
      {
        "name": "const",
        "reference": "type_const"
      }
    ]
  },
  "string": {
    "name": "string",
    "description": "Keyword used to explicitly declare the \"string\" type of a variable or a parameter.",
    "example": "//@version=6indicator(\"string\")string s = \"Hello World!\"    // Same as `s = \"Hello world!\"`// string s = na // same as \"\"plot(na, title=s)",
    "remarks": "Explicitly mentioning the type in a variable declaration is optional, except when it is initialized with na. Learn more about Pine Script® types in the User Manual page on the Type System.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "varip",
        "reference": "kw_varip"
      },
      {
        "name": "int",
        "reference": "type_int"
      },
      {
        "name": "float",
        "reference": "type_float"
      },
      {
        "name": "bool",
        "reference": "type_bool"
      },
      {
        "name": "str.tostring",
        "reference": "fun_str.tostring"
      },
      {
        "name": "str.format",
        "reference": "fun_str.format"
      }
    ]
  },
  "table": {
    "name": "table",
    "description": "Keyword used to explicitly declare the \"table\" type of a variable or a parameter. Table objects (or IDs) can be created with the table.new function.",
    "example": "//@version=6indicator(\"table\")// Empty `table1` table ID.var table table1 = na// `table` type is unnecessary because `table.new()` returns \"table\" type.var table2 = table.new(position.top_left, na, na)if barstate.islastconfirmedhistory    var table3 = table.new(position = position.top_right, columns = 1, rows = 1, bgcolor = color.yellow, border_width = 1)    table.cell(table_id = table3, column = 0, row = 0, text = \"table3 text\")",
    "remarks": "Table objects are always of \"series\" form.",
    "seeAlso": [
      {
        "name": "var",
        "reference": "kw_var"
      },
      {
        "name": "line",
        "reference": "type_line"
      },
      {
        "name": "label",
        "reference": "type_label"
      },
      {
        "name": "box",
        "reference": "type_box"
      },
      {
        "name": "table.new",
        "reference": "fun_table.new"
      }
    ]
  }
} as const;
