// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © KioseffTrading

//@version=5
indicator("Tick CVD [Kioseff Trading]", max_labels_count = 500, max_lines_count = 500, max_boxes_count = 500, 
             max_polylines_count = 100, overlay = false)

import RicardoSantos/MathOperator/2
import kaigouthro/hsvColor/16 as kai 

enum visual 

    aesthetic = "Aesthetic"
    efficient = "Efficient"

enum lineT 

    line   = "Line"
    candle = "Candle"

plot(close)
