// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International  
// https://creativecommons.org/licenses/by-nc-sa/4.0/
// © Zeiierman {
//@version=6
indicator("Volume Profile 3D (Zeiierman)",overlay = true,max_polylines_count = 100)
//}
// ~~ UDT's {
type Arrays
    array<float> v
    array<float> c
    array<float> o
    array<float> m
//~~}
// ~~ Variables {
var a   = Arrays.new(array.new<float>(),
 array.new<float>(),
 array.new<float>(),
 array.new<float>())
//~~}
// ~~ Functions {
method CandlestickData(Arrays arr)=>
    arr.v.push(volume)
    arr.c.push(close)
    arr.o.push(open)
    arr.m.push(hl2)

method CandlestickDataClean(Arrays arr)=>
    arr.v.shift()
    arr.c.shift()
    arr.o.shift()
    arr.m.shift()

GradientColorSingle(c, size, max)=>
    factor = max > 0 ? size / max : 0.0
    factor := math.min(1.0, math.max(0.0, factor))
    baseTransp = 90
    maxTransp  = 10
    transp = math.round(baseTransp * (1 - factor) + maxTransp * factor)
    color.new(c, transp)
//~~}
// ~~ Main {
if barstate.isfirst
    a.CandlestickData()
//~}
//~~}
