// This file is automatically generated by scripts/extract-syntax-structures.ts.
// Do not edit this file directly.

import type { AnnotationMap } from './schema';

export const annotations = {
  "@description": {
    "syntax": []
  },
  "@enum": {
    "syntax": []
  },
  "@field": {
    "syntax": []
  },
  "@function": {
    "syntax": []
  },
  "@param": {
    "syntax": []
  },
  "@returns": {
    "syntax": []
  },
  "@strategy_alert_message": {
    "syntax": []
  },
  "@type": {
    "syntax": []
  },
  "@variable": {
    "syntax": []
  }
} satisfies AnnotationMap;
export type Annotations = typeof annotations;

