// This file is automatically generated by scripts/extract-syntax-structures.ts.
// Do not edit this file directly.

import { defineConstant } from './schema';
import type { ConstantMap } from './schema';

export const constants = {
  "adjustment": {
    "dividends": defineConstant({qualifier: "const", type: "string"}),
    "none": defineConstant({qualifier: "const", type: "string"}),
    "splits": defineConstant({qualifier: "const", type: "string"})
  },
  "alert": {
    "freq_all": defineConstant({qualifier: "const", type: "string"}),
    "freq_once_per_bar": defineConstant({qualifier: "const", type: "string"}),
    "freq_once_per_bar_close": defineConstant({qualifier: "const", type: "string"})
  },
  "backadjustment": {
    "inherit": defineConstant({qualifier: "const", type: "backadjustment"}),
    "off": defineConstant({qualifier: "const", type: "backadjustment"}),
    "on": defineConstant({qualifier: "const", type: "backadjustment"})
  },
  "barmerge": {
    "gaps_off": defineConstant({qualifier: "const", type: "barmerge_gaps"}),
    "gaps_on": defineConstant({qualifier: "const", type: "barmerge_gaps"}),
    "lookahead_off": defineConstant({qualifier: "const", type: "barmerge_lookahead"}),
    "lookahead_on": defineConstant({qualifier: "const", type: "barmerge_lookahead"})
  },
  "Bitcoin": defineConstant({qualifier: "const", type: "string"}),
  "color": {
    "aqua": defineConstant({qualifier: "const", type: "color"}),
    "black": defineConstant({qualifier: "const", type: "color"}),
    "blue": defineConstant({qualifier: "const", type: "color"}),
    "fuchsia": defineConstant({qualifier: "const", type: "color"}),
    "gray": defineConstant({qualifier: "const", type: "color"}),
    "green": defineConstant({qualifier: "const", type: "color"}),
    "lime": defineConstant({qualifier: "const", type: "color"}),
    "maroon": defineConstant({qualifier: "const", type: "color"}),
    "navy": defineConstant({qualifier: "const", type: "color"}),
    "olive": defineConstant({qualifier: "const", type: "color"}),
    "orange": defineConstant({qualifier: "const", type: "color"}),
    "purple": defineConstant({qualifier: "const", type: "color"}),
    "red": defineConstant({qualifier: "const", type: "color"}),
    "silver": defineConstant({qualifier: "const", type: "color"}),
    "teal": defineConstant({qualifier: "const", type: "color"}),
    "white": defineConstant({qualifier: "const", type: "color"}),
    "yellow": defineConstant({qualifier: "const", type: "color"})
  },
  "currency": {
    "AED": defineConstant({qualifier: "const", type: "string"}),
    "ARS": defineConstant({qualifier: "const", type: "string"}),
    "AUD": defineConstant({qualifier: "const", type: "string"}),
    "BDT": defineConstant({qualifier: "const", type: "string"}),
    "BHD": defineConstant({qualifier: "const", type: "string"}),
    "BRL": defineConstant({qualifier: "const", type: "string"}),
    "CAD": defineConstant({qualifier: "const", type: "string"}),
    "CHF": defineConstant({qualifier: "const", type: "string"}),
    "CLP": defineConstant({qualifier: "const", type: "string"}),
    "CNY": defineConstant({qualifier: "const", type: "string"}),
    "COP": defineConstant({qualifier: "const", type: "string"}),
    "CZK": defineConstant({qualifier: "const", type: "string"}),
    "DKK": defineConstant({qualifier: "const", type: "string"}),
    "EGP": defineConstant({qualifier: "const", type: "string"}),
    "GBP": defineConstant({qualifier: "const", type: "string"}),
    "HKD": defineConstant({qualifier: "const", type: "string"}),
    "HUF": defineConstant({qualifier: "const", type: "string"}),
    "IDR": defineConstant({qualifier: "const", type: "string"}),
    "ILS": defineConstant({qualifier: "const", type: "string"}),
    "INR": defineConstant({qualifier: "const", type: "string"}),
    "ISK": defineConstant({qualifier: "const", type: "string"}),
    "JPY": defineConstant({qualifier: "const", type: "string"}),
    "KES": defineConstant({qualifier: "const", type: "string"}),
    "KRW": defineConstant({qualifier: "const", type: "string"}),
    "KWD": defineConstant({qualifier: "const", type: "string"}),
    "LKR": defineConstant({qualifier: "const", type: "string"}),
    "MAD": defineConstant({qualifier: "const", type: "string"}),
    "MXN": defineConstant({qualifier: "const", type: "string"}),
    "MYR": defineConstant({qualifier: "const", type: "string"}),
    "NGN": defineConstant({qualifier: "const", type: "string"}),
    "NOK": defineConstant({qualifier: "const", type: "string"}),
    "NONE": defineConstant({qualifier: "const", type: "string"}),
    "NZD": defineConstant({qualifier: "const", type: "string"}),
    "PEN": defineConstant({qualifier: "const", type: "string"}),
    "PHP": defineConstant({qualifier: "const", type: "string"}),
    "PKR": defineConstant({qualifier: "const", type: "string"}),
    "PLN": defineConstant({qualifier: "const", type: "string"}),
    "QAR": defineConstant({qualifier: "const", type: "string"}),
    "RON": defineConstant({qualifier: "const", type: "string"}),
    "RSD": defineConstant({qualifier: "const", type: "string"}),
    "RUB": defineConstant({qualifier: "const", type: "string"}),
    "SAR": defineConstant({qualifier: "const", type: "string"}),
    "SEK": defineConstant({qualifier: "const", type: "string"}),
    "SGD": defineConstant({qualifier: "const", type: "string"}),
    "THB": defineConstant({qualifier: "const", type: "string"}),
    "TND": defineConstant({qualifier: "const", type: "string"}),
    "TRY": defineConstant({qualifier: "const", type: "string"}),
    "TWD": defineConstant({qualifier: "const", type: "string"}),
    "USD": defineConstant({qualifier: "const", type: "string"}),
    "VES": defineConstant({qualifier: "const", type: "string"}),
    "VND": defineConstant({qualifier: "const", type: "string"}),
    "ZAR": defineConstant({qualifier: "const", type: "string"})
  },
  "dayofweek": {
    "friday": defineConstant({qualifier: "const", type: "int"}),
    "monday": defineConstant({qualifier: "const", type: "int"}),
    "saturday": defineConstant({qualifier: "const", type: "int"}),
    "sunday": defineConstant({qualifier: "const", type: "int"}),
    "thursday": defineConstant({qualifier: "const", type: "int"}),
    "tuesday": defineConstant({qualifier: "const", type: "int"}),
    "wednesday": defineConstant({qualifier: "const", type: "int"})
  },
  "display": {
    "all": defineConstant({qualifier: "const", type: "plot_simple_display"}),
    "data_window": defineConstant({qualifier: "const", type: "plot_display"}),
    "none": defineConstant({qualifier: "const", type: "plot_simple_display"}),
    "pane": defineConstant({qualifier: "const", type: "plot_display"}),
    "price_scale": defineConstant({qualifier: "const", type: "plot_display"}),
    "status_line": defineConstant({qualifier: "const", type: "plot_display"})
  },
  "dividends": {
    "gross": defineConstant({qualifier: "const", type: "string"}),
    "net": defineConstant({qualifier: "const", type: "string"})
  },
  "earnings": {
    "actual": defineConstant({qualifier: "const", type: "string"}),
    "estimate": defineConstant({qualifier: "const", type: "string"}),
    "standardized": defineConstant({qualifier: "const", type: "string"})
  },
  "Ethereum": defineConstant({qualifier: "const", type: "string"}),
  "Euro": defineConstant({qualifier: "const", type: "string"}),
  "extend": {
    "both": defineConstant({qualifier: "const", type: "string"}),
    "left": defineConstant({qualifier: "const", type: "string"}),
    "none": defineConstant({qualifier: "const", type: "string"}),
    "right": defineConstant({qualifier: "const", type: "string"})
  },
  "font": {
    "family_default": defineConstant({qualifier: "const", type: "string"}),
    "family_monospace": defineConstant({qualifier: "const", type: "string"})
  },
  "format": {
    "inherit": defineConstant({qualifier: "const", type: "string"}),
    "mintick": defineConstant({qualifier: "const", type: "string"}),
    "percent": defineConstant({qualifier: "const", type: "string"}),
    "price": defineConstant({qualifier: "const", type: "string"}),
    "volume": defineConstant({qualifier: "const", type: "string"})
  },
  "hline": {
    "style_dashed": defineConstant({qualifier: "const", type: "hline_style"}),
    "style_dotted": defineConstant({qualifier: "const", type: "hline_style"}),
    "style_solid": defineConstant({qualifier: "const", type: "hline_style"})
  },
  "label": {
    "style_arrowdown": defineConstant({qualifier: "const", type: "string"}),
    "style_arrowup": defineConstant({qualifier: "const", type: "string"}),
    "style_circle": defineConstant({qualifier: "const", type: "string"}),
    "style_cross": defineConstant({qualifier: "const", type: "string"}),
    "style_diamond": defineConstant({qualifier: "const", type: "string"}),
    "style_flag": defineConstant({qualifier: "const", type: "string"}),
    "style_label_center": defineConstant({qualifier: "const", type: "string"}),
    "style_label_down": defineConstant({qualifier: "const", type: "string"}),
    "style_label_left": defineConstant({qualifier: "const", type: "string"}),
    "style_label_lower_left": defineConstant({qualifier: "const", type: "string"}),
    "style_label_lower_right": defineConstant({qualifier: "const", type: "string"}),
    "style_label_right": defineConstant({qualifier: "const", type: "string"}),
    "style_label_up": defineConstant({qualifier: "const", type: "string"}),
    "style_label_upper_left": defineConstant({qualifier: "const", type: "string"}),
    "style_label_upper_right": defineConstant({qualifier: "const", type: "string"}),
    "style_none": defineConstant({qualifier: "const", type: "string"}),
    "style_square": defineConstant({qualifier: "const", type: "string"}),
    "style_text_outline": defineConstant({qualifier: "const", type: "string"}),
    "style_triangledown": defineConstant({qualifier: "const", type: "string"}),
    "style_triangleup": defineConstant({qualifier: "const", type: "string"}),
    "style_xcross": defineConstant({qualifier: "const", type: "string"})
  },
  "line": {
    "style_arrow_both": defineConstant({qualifier: "const", type: "string"}),
    "style_arrow_left": defineConstant({qualifier: "const", type: "string"}),
    "style_arrow_right": defineConstant({qualifier: "const", type: "string"}),
    "style_dashed": defineConstant({qualifier: "const", type: "string"}),
    "style_dotted": defineConstant({qualifier: "const", type: "string"}),
    "style_solid": defineConstant({qualifier: "const", type: "string"})
  },
  "location": {
    "abovebar": defineConstant({qualifier: "const", type: "string"}),
    "absolute": defineConstant({qualifier: "const", type: "string"}),
    "belowbar": defineConstant({qualifier: "const", type: "string"}),
    "bottom": defineConstant({qualifier: "const", type: "string"}),
    "top": defineConstant({qualifier: "const", type: "string"})
  },
  "math": {
    "e": defineConstant({qualifier: "const", type: "float"}),
    "phi": defineConstant({qualifier: "const", type: "float"}),
    "pi": defineConstant({qualifier: "const", type: "float"}),
    "rphi": defineConstant({qualifier: "const", type: "float"})
  },
  "order": {
    "ascending": defineConstant({qualifier: "const", type: "sort_order"}),
    "descending": defineConstant({qualifier: "const", type: "sort_order"})
  },
  "plot": {
    "style_area": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_areabr": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_circles": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_columns": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_cross": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_histogram": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_line": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_linebr": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_stepline": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_stepline_diamond": defineConstant({qualifier: "const", type: "plot_style"}),
    "style_steplinebr": defineConstant({qualifier: "const", type: "plot_style"})
  },
  "position": {
    "bottom_center": defineConstant({qualifier: "const", type: "string"}),
    "bottom_left": defineConstant({qualifier: "const", type: "string"}),
    "bottom_right": defineConstant({qualifier: "const", type: "string"}),
    "middle_center": defineConstant({qualifier: "const", type: "string"}),
    "middle_left": defineConstant({qualifier: "const", type: "string"}),
    "middle_right": defineConstant({qualifier: "const", type: "string"}),
    "top_center": defineConstant({qualifier: "const", type: "string"}),
    "top_left": defineConstant({qualifier: "const", type: "string"}),
    "top_right": defineConstant({qualifier: "const", type: "string"})
  },
  "scale": {
    "left": defineConstant({qualifier: "const", type: "scale_type"}),
    "none": defineConstant({qualifier: "const", type: "scale_type"}),
    "right": defineConstant({qualifier: "const", type: "scale_type"})
  },
  "session": {
    "extended": defineConstant({qualifier: "const", type: "string"}),
    "regular": defineConstant({qualifier: "const", type: "string"})
  },
  "settlement_as_close": {
    "inherit": defineConstant({qualifier: "const", type: "settlement"}),
    "off": defineConstant({qualifier: "const", type: "settlement"}),
    "on": defineConstant({qualifier: "const", type: "settlement"})
  },
  "shape": {
    "arrowdown": defineConstant({qualifier: "const", type: "string"}),
    "arrowup": defineConstant({qualifier: "const", type: "string"}),
    "circle": defineConstant({qualifier: "const", type: "string"}),
    "cross": defineConstant({qualifier: "const", type: "string"}),
    "diamond": defineConstant({qualifier: "const", type: "string"}),
    "flag": defineConstant({qualifier: "const", type: "string"}),
    "labeldown": defineConstant({qualifier: "const", type: "string"}),
    "labelup": defineConstant({qualifier: "const", type: "string"}),
    "square": defineConstant({qualifier: "const", type: "string"}),
    "triangledown": defineConstant({qualifier: "const", type: "string"}),
    "triangleup": defineConstant({qualifier: "const", type: "string"}),
    "xcross": defineConstant({qualifier: "const", type: "string"})
  },
  "size": {
    "auto": defineConstant({qualifier: "const", type: "string"}),
    "huge": defineConstant({qualifier: "const", type: "string"}),
    "large": defineConstant({qualifier: "const", type: "string"}),
    "normal": defineConstant({qualifier: "const", type: "string"}),
    "small": defineConstant({qualifier: "const", type: "string"}),
    "tiny": defineConstant({qualifier: "const", type: "string"})
  },
  "splits": {
    "denominator": defineConstant({qualifier: "const", type: "string"}),
    "numerator": defineConstant({qualifier: "const", type: "string"})
  },
  "strategy": {
    "cash": defineConstant({qualifier: "const", type: "string"}),
    "commission": {
      "cash_per_contract": defineConstant({qualifier: "const", type: "string"}),
      "cash_per_order": defineConstant({qualifier: "const", type: "string"}),
      "percent": defineConstant({qualifier: "const", type: "string"})
    },
    "direction": {
      "all": defineConstant({qualifier: "const", type: "string"}),
      "long": defineConstant({qualifier: "const", type: "string"}),
      "short": defineConstant({qualifier: "const", type: "string"})
    },
    "fixed": defineConstant({qualifier: "const", type: "string"}),
    "long": defineConstant({qualifier: "const", type: "strategy_direction"}),
    "oca": {
      "cancel": defineConstant({qualifier: "const", type: "string"}),
      "none": defineConstant({qualifier: "const", type: "string"}),
      "reduce": defineConstant({qualifier: "const", type: "string"})
    },
    "percent_of_equity": defineConstant({qualifier: "const", type: "string"}),
    "short": defineConstant({qualifier: "const", type: "strategy_direction"})
  },
  "Tether": defineConstant({qualifier: "const", type: "string"}),
  "text": {
    "align_bottom": defineConstant({qualifier: "const", type: "string"}),
    "align_center": defineConstant({qualifier: "const", type: "string"}),
    "align_left": defineConstant({qualifier: "const", type: "string"}),
    "align_right": defineConstant({qualifier: "const", type: "string"}),
    "align_top": defineConstant({qualifier: "const", type: "string"}),
    "format_bold": defineConstant({qualifier: "const", type: "text_format"}),
    "format_italic": defineConstant({qualifier: "const", type: "text_format"}),
    "format_none": defineConstant({qualifier: "const", type: "text_format"}),
    "wrap_auto": defineConstant({qualifier: "const", type: "string"}),
    "wrap_none": defineConstant({qualifier: "const", type: "string"})
  },
  "xloc": {
    "bar_index": defineConstant({qualifier: "const", type: "string"}),
    "bar_time": defineConstant({qualifier: "const", type: "string"})
  },
  "yloc": {
    "abovebar": defineConstant({qualifier: "const", type: "string"}),
    "belowbar": defineConstant({qualifier: "const", type: "string"}),
    "price": defineConstant({qualifier: "const", type: "string"})
  }
} satisfies ConstantMap;
export type Constants = typeof constants;

