// This file is automatically generated by scripts/extract-syntax-structures.ts.
// Do not edit this file directly.

import { functions } from './functions';
import { variables } from './variables';
import { constants } from './constants';
import { operators } from './operators';
import { keywords } from './keywords';
import { types } from './types';
import { annotations } from './annotations';
import type { Functions } from './functions';
import type { Variables } from './variables';
import type { Constants } from './constants';
import type { Operators } from './operators';
import type { Keywords } from './keywords';
import type { Types } from './types';
import type { Annotations } from './annotations';

export { functions } from './functions';
export type { Functions } from './functions';
export { variables } from './variables';
export type { Variables } from './variables';
export { constants } from './constants';
export type { Constants } from './constants';
export { operators } from './operators';
export type { Operators } from './operators';
export { keywords } from './keywords';
export type { Keywords } from './keywords';
export { types } from './types';
export type { Types } from './types';
export { annotations } from './annotations';
export type { Annotations } from './annotations';

export type {
  PineTypeName,
  PineQualifier,
  PineTypeTagged,
  PineFunctionSignature,
  PineFunctionArgument,
  PineFunctionEntry,
  PineVariableEntry,
  PineConstantEntry,
  PineOperatorEntry,
  PineKeywordEntry,
  PineTypeField,
  PineTypeEntry,
  PineAnnotationEntry,
  NestedRecord,
  FunctionMap,
  VariableMap,
  ConstantMap,
  OperatorMap,
  KeywordMap,
  TypeMap,
  AnnotationMap
} from './schema';

export const pineManualStructures = {
  functions,
  variables,
  constants,
  operators,
  keywords,
  types,
  annotations
} as const;
export type PineManualStructures = typeof pineManualStructures;

