// This file is automatically generated by scripts/extract-syntax-structures.ts.
// Do not edit this file directly.

import type { OperatorMap } from './schema';

export const operators = {
  "-": [
    "expr1 - expr2"
  ],
  "-=": [
    "expr1 -= expr2"
  ],
  ":=": [
    "<var_name> := <new_value>"
  ],
  "!=": [
    "expr1 != expr2"
  ],
  "?:": [
    "expr1 ? expr2 : expr3"
  ],
  "[]": [
    "expr1[expr2]"
  ],
  "*": [
    "expr1 * expr2"
  ],
  "*=": [
    "expr1 *= expr2"
  ],
  "/": [
    "expr1 / expr2"
  ],
  "/=": [
    "expr1 /= expr2"
  ],
  "%": [
    "expr1 % expr2"
  ],
  "%=": [
    "expr1 %= expr2"
  ],
  "+": [
    "expr1 + expr2"
  ],
  "+=": [
    "expr1 += expr2"
  ],
  "<": [
    "expr1 < expr2"
  ],
  "<=": [
    "expr1 <= expr2"
  ],
  "==": [
    "expr1 == expr2"
  ],
  "=>": [
    "<identifier>([<parameter_name>[=<default_value>]], ...) =>",
    "<local_block>",
    "<function_result>",
    "A <local_block> is zero or more Pine Script® statements.",
    "The <function_result> is a variable, an expression, or a tuple."
  ],
  ">": [
    "expr1 > expr2"
  ],
  ">=": [
    "expr1 >= expr2"
  ]
} satisfies OperatorMap;
export type Operators = typeof operators;

