// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: 2025-10-03T21:07:53.685Z

export interface PineOperatorMetadata {
  readonly name: string;
  readonly description: string;
  readonly syntax: string;
  readonly example?: string;
  readonly remarks?: string;
  readonly returns?: string;
}

export const operators: Record<string, PineOperatorMetadata> = {
  "-": {
    "name": "-",
    "description": "Subtraction or unary minus. Applicable to numerical expressions.",
    "syntax": "expr1 - expr2",
    "remarks": "You may use arithmetic operators with numbers as well as with series variables. In case of usage with series the operators are applied elementwise.",
    "returns": "Returns integer or float value, or series of values:"
  },
  "-=": {
    "name": "-=",
    "description": "Subtraction assignment. Applicable to numerical expressions.",
    "syntax": "expr1 -= expr2",
    "example": "//@version=6indicator(\"-=\")// Equals to expr1 = expr1 - expr2.a = 2b = 3a -= b// Result: a = -1.plot(a)",
    "returns": "Integer or float value, or series of values."
  },
  ":=": {
    "name": ":=",
    "description": "Reassignment operator. It is used to assign a new value to a previously declared variable.",
    "syntax": "<var_name> := <new_value>",
    "example": "//@version=6indicator(\"My script\")myVar = 10if close > open    // Modifies the existing global scope `myVar` variable by changing its value from 10 to 20.    myVar := 20    // Creates a new `myVar` variable local to the `if` condition and unreachable from the global scope.    // Does not affect the `myVar` declared in global scope.    myVar = 30plot(myVar)"
  },
  "!=": {
    "name": "!=",
    "description": "Inequality operator. Returns true if the operands are considered not equal, and false otherwise. This operator is compatible with all value types, including \"int\", \"float\", \"bool\", \"color\", and \"string\". The operator can also compare two line or label IDs.",
    "syntax": "expr1 != expr2",
    "remarks": "This operator rounds \"float\" operands to nine fractional digits.",
    "returns": "Boolean value, or series of boolean values."
  },
  "?:": {
    "name": "?:",
    "description": "Ternary conditional operator.",
    "syntax": "expr1 ? expr2 : expr3",
    "example": "//@version=6indicator(\"?:\")// Draw circles at the bars where open crosses closes2 = ta.cross(open, close) ? math.avg(open,close) : naplot(s2, style=plot.style_circles, linewidth=2, color=color.red)// Combination of ?: operators for 'switch'-like logicc = timeframe.isintraday ? color.red : timeframe.isdaily ? color.green : timeframe.isweekly ? color.blue : color.grayplot(hl2, color=c)",
    "remarks": "Use na for 'else' branch if you do not need it.",
    "returns": "expr2 if expr1 is evaluated to true, expr3 otherwise. Zero value (0 and also NaN, +Infinity, -Infinity) is considered to be false, any other value is true."
  },
  "[]": {
    "name": "[]",
    "description": "Series subscript. Provides access to previous values of series expr1. expr2 is the number of bars back, and must be numerical. Floats will be rounded down.",
    "syntax": "expr1[expr2]",
    "example": "//@version=6indicator(\"[]\")// [] can be used to \"save\" variable value between barsa = 0.0 // declare `a`a := a[1] // immediately set current value to the same as previous. `na` in the beginning of historyif high == low // if some condition - change `a` value to another    a := lowplot(a)",
    "returns": "A series of values."
  },
  "*": {
    "name": "*",
    "description": "Multiplication. Applicable to numerical expressions.",
    "syntax": "expr1 * expr2",
    "returns": "Integer or float value, or series of values."
  },
  "*=": {
    "name": "*=",
    "description": "Multiplication assignment. Applicable to numerical expressions.",
    "syntax": "expr1 *= expr2",
    "example": "//@version=6indicator(\"*=\")// Equals to expr1 = expr1 * expr2.a = 2b = 3a *= b// Result: a = 6.plot(a)",
    "returns": "Integer or float value, or series of values."
  },
  "/": {
    "name": "/",
    "description": "Division. Applicable to numerical expressions.",
    "syntax": "expr1 / expr2",
    "returns": "Integer or float value, or series of values."
  },
  "/=": {
    "name": "/=",
    "description": "Division assignment. Applicable to numerical expressions.",
    "syntax": "expr1 /= expr2",
    "example": "//@version=6indicator(\"/=\")// Equals to expr1 = expr1 / expr2.float a = 3.0b = 3a /= b// Result: a = 1.plot(a)",
    "returns": "Integer or float value, or series of values."
  },
  "%": {
    "name": "%",
    "description": "Modulo (integer remainder). Applicable to numerical expressions.",
    "syntax": "expr1 % expr2",
    "remarks": "In Pine Script®, when the integer remainder is calculated, the quotient is truncated, i.e. rounded towards the lowest absolute value. The resulting value will have the same sign as the dividend.",
    "returns": "Integer or float value, or series of values."
  },
  "%=": {
    "name": "%=",
    "description": "Modulo assignment. Applicable to numerical expressions.",
    "syntax": "expr1 %= expr2",
    "example": "//@version=6indicator(\"%=\")// Equals to expr1 = expr1 % expr2.a = 3b = 3a %= b// Result: a = 0.plot(a)",
    "returns": "Integer or float value, or series of values."
  },
  "+": {
    "name": "+",
    "description": "Addition or unary plus. Applicable to numerical expressions or strings.",
    "syntax": "expr1 + expr2",
    "remarks": "You may use arithmetic operators with numbers as well as with series variables. In case of usage with series the operators are applied elementwise.",
    "returns": "Binary + for strings returns concatenation of expr1 and expr2"
  },
  "+=": {
    "name": "+=",
    "description": "Addition assignment. Applicable to numerical expressions or strings.",
    "syntax": "expr1 += expr2",
    "example": "//@version=6indicator(\"+=\")// Equals to expr1 = expr1 + expr2.a = 2b = 3a += b// Result: a = 5.plot(a)",
    "remarks": "You may use arithmetic operators with numbers as well as with series variables. In case of usage with series the operators are applied elementwise.",
    "returns": "For strings returns concatenation of expr1 and expr2. For numbers returns integer or float value, or series of values."
  },
  "<": {
    "name": "<",
    "description": "Less than. Applicable to numerical expressions.",
    "syntax": "expr1 < expr2",
    "returns": "Boolean value, or series of boolean values."
  },
  "<=": {
    "name": "<=",
    "description": "Less than or equal to. Applicable to numerical expressions.",
    "syntax": "expr1 <= expr2",
    "returns": "Boolean value, or series of boolean values."
  },
  "=": {
    "name": "=",
    "description": "Assignment operator. Assigns an initial value or reference to a declared variable. It means this is a new variable, and it starts with this value.",
    "syntax": "<var_name> := <initial_value>",
    "example": "//@version=6indicator(\"`=` showcase\")// The following are all valid variable declarations.i = 1MS_IN_ONE_MINUTE = 1000 * 60showPlotInput = input.bool(true, \"Show plots\")pHi = ta.pivothigh(5, 5)plotColor = color.greenplot(pHi, color = plotColor, display = showPlotInput ? display.all : display.none, precision = i)"
  },
  "==": {
    "name": "==",
    "description": "Equality operator. Returns true if the operands are considered equal, and false otherwise. This operator is compatible with all value types, including \"int\", \"float\", \"bool\", \"color\", and \"string\". The operator can also compare two line or label IDs.",
    "syntax": "expr1 == expr2",
    "remarks": "This operator rounds \"float\" operands to nine fractional digits.",
    "returns": "Boolean value, or series of boolean values."
  },
  "=>": {
    "name": "=>",
    "description": "The '=>' operator is used in user-defined function declarations and in switch statements.",
    "syntax": "<identifier>([<parameter_name>[=<default_value>]], ...) =>\n    <local_block>\n    <function_result>",
    "example": "//@version=6indicator(\"=>\")// single-line functionf1(x, y) => x + y// multi-line functionf2(x, y) =>    sum = x + y    sumChange = ta.change(sum, 10)    // Function automatically returns the last expression used in itplot(f1(30, 8) + f2(1, 3))",
    "remarks": "You can learn more about user-defined functions in the User Manual's pages on Declaring functions and Libraries."
  },
  ">": {
    "name": ">",
    "description": "Greater than. Applicable to numerical expressions.",
    "syntax": "expr1 > expr2",
    "returns": "Boolean value, or series of boolean values."
  },
  ">=": {
    "name": ">=",
    "description": "Greater than or equal to. Applicable to numerical expressions.",
    "syntax": "expr1 >= expr2",
    "returns": "Boolean value, or series of boolean values."
  }
} as const;
