// This file is automatically generated by scripts/extract-syntax-structures.ts.
// Do not edit this file directly.

export type PineTypeName = string | null;
export type PineQualifier = 'series' | 'simple' | 'input' | 'const' | null;

export type PineTypeTagged<Name extends PineTypeName> = {
  readonly __pineType?: Name;
};

export type PineFunctionSignature<Name extends PineTypeName> = PineTypeTagged<Name> & {
  readonly params: readonly string[];
  readonly returnType: Name;
  readonly text: string;
};

export type PineFunctionArgument<
  Name extends string,
  Qualifier extends PineQualifier,
  TypeName extends PineTypeName
> = PineTypeTagged<TypeName> & {
  readonly name: Name;
  readonly qualifier: Qualifier;
  readonly required: boolean;
  readonly default: string | null;
};

export type PineFunctionEntry = {
  readonly signatures: readonly PineFunctionSignature<PineTypeName>[];
  readonly arguments: readonly PineFunctionArgument<string, PineQualifier, PineTypeName>[];
};

export type PineVariableEntry = PineTypeTagged<PineTypeName> & {
  readonly qualifier: PineQualifier;
};

export type PineConstantEntry = PineTypeTagged<PineTypeName> & {
  readonly qualifier: PineQualifier;
};

export type PineOperatorEntry = readonly string[];

export type PineKeywordEntry = {
  readonly syntax: readonly string[];
};

export type PineTypeField = PineTypeTagged<PineTypeName> & {
  readonly name: string;
  readonly qualifier: PineQualifier;
  readonly description: string | null;
};

export type PineTypeEntry = {
  readonly syntax: readonly string[];
  readonly fields: readonly PineTypeField[];
};

export type PineAnnotationEntry = {
  readonly syntax: readonly string[];
};

export type NestedRecord<T> = {
  readonly [key: string]: T | NestedRecord<T>;
};

type FunctionSignatureInit<Name extends PineTypeName> = {
  readonly params: readonly string[];
  readonly returnType: Name;
  readonly text: string;
};

type FunctionArgumentInit<
  Name extends string,
  Qualifier extends PineQualifier,
  TypeName extends PineTypeName
> = {
  readonly name: Name;
  readonly qualifier: Qualifier;
  readonly type: TypeName;
  readonly required: boolean;
  readonly default: string | null;
};

type VariableInit<TypeName extends PineTypeName> = {
  readonly qualifier: PineQualifier;
  readonly type: TypeName;
};

type ConstantInit<TypeName extends PineTypeName> = {
  readonly qualifier: PineQualifier;
  readonly type: TypeName;
};

type TypeFieldInit<
  Name extends string,
  Qualifier extends PineQualifier,
  TypeName extends PineTypeName
> = {
  readonly name: Name;
  readonly qualifier: Qualifier;
  readonly type: TypeName;
  readonly description: string | null;
};

export const defineFunctionSignature = <Name extends PineTypeName>(
  signature: FunctionSignatureInit<Name>,
): PineFunctionSignature<Name> => signature as PineFunctionSignature<Name>;

export const defineFunctionArgument = <
  Name extends string,
  Qualifier extends PineQualifier,
  TypeName extends PineTypeName
>({
  name,
  qualifier,
  type,
  required,
  default: defaultValue,
}: FunctionArgumentInit<Name, Qualifier, TypeName>): PineFunctionArgument<Name, Qualifier, TypeName> => {
  void type;
  return {
    name,
    qualifier,
    required,
    default: defaultValue,
  } as PineFunctionArgument<Name, Qualifier, TypeName>;
};

export const defineVariable = <TypeName extends PineTypeName>({
  qualifier,
  type,
}: VariableInit<TypeName>): PineVariableEntry => {
  void type;
  return {
    qualifier,
  } as PineVariableEntry;
};

export const defineConstant = <TypeName extends PineTypeName>({
  qualifier,
  type,
}: ConstantInit<TypeName>): PineConstantEntry => {
  void type;
  return {
    qualifier,
  } as PineConstantEntry;
};

export const defineTypeField = <
  Name extends string,
  Qualifier extends PineQualifier,
  TypeName extends PineTypeName
>({ name, qualifier, type, description }: TypeFieldInit<Name, Qualifier, TypeName>): PineTypeField => {
  void type;
  return {
    name,
    qualifier,
    description,
  } as PineTypeField;
};

export type FunctionMap = NestedRecord<PineFunctionEntry>;
export type VariableMap = NestedRecord<PineVariableEntry>;
export type ConstantMap = NestedRecord<PineConstantEntry>;
export type OperatorMap = NestedRecord<PineOperatorEntry>;
export type KeywordMap = NestedRecord<PineKeywordEntry>;
export type TypeMap = NestedRecord<PineTypeEntry>;
export type AnnotationMap = NestedRecord<PineAnnotationEntry>;

