// This file is automatically generated by scripts/extract-syntax-structures.ts.
// Do not edit this file directly.

import { defineTypeField } from './schema';
import type { TypeMap } from './schema';

export const types = {
  "array": {
    "fields": [
    ],
    "from": {
      "fields": [
      ],
      "syntax": []
    },
    "new<type>": {
      "fields": [
      ],
      "syntax": []
    },
    "syntax": []
  },
  "bool": {
    "fields": [
    ],
    "syntax": []
  },
  "box": {
    "fields": [
    ],
    "new": {
      "fields": [
      ],
      "syntax": []
    },
    "syntax": []
  },
  "chart": {
    "point": {
      "fields": [
        defineTypeField({name: "index", qualifier: "series", type: "int", description: "The x-coordinate of the point, expressed as a bar index value."}),
        defineTypeField({name: "time", qualifier: "series", type: "int", description: "The x-coordinate of the point, expressed as a UNIX time value, in milliseconds."}),
        defineTypeField({name: "price", qualifier: "series", type: "float", description: "The y-coordinate of the point."})
      ],
      "syntax": []
    }
  },
  "color": {
    "fields": [
    ],
    "new": {
      "fields": [
      ],
      "syntax": []
    },
    "rgb": {
      "fields": [
      ],
      "syntax": []
    },
    "syntax": []
  },
  "const": {
    "fields": [
    ],
    "syntax": [
      "[method ]<functionName>([const <paramType> ]<paramName>[ = <defaultValue>])",
      "[var/varip ]const <variableType> <variableName> = <variableValue>"
    ]
  },
  "false": {
    "fields": [
    ],
    "syntax": []
  },
  "float": {
    "fields": [
    ],
    "syntax": []
  },
  "int": {
    "fields": [
    ],
    "syntax": []
  },
  "label": {
    "fields": [
    ],
    "new": {
      "fields": [
      ],
      "syntax": []
    },
    "syntax": []
  },
  "line": {
    "fields": [
    ],
    "new": {
      "fields": [
      ],
      "syntax": []
    },
    "syntax": []
  },
  "linefill": {
    "fields": [
    ],
    "new": {
      "fields": [
      ],
      "syntax": []
    },
    "syntax": []
  },
  "map": {
    "fields": [
    ],
    "syntax": []
  },
  "matrix": {
    "fields": [
    ],
    "new<type>": {
      "fields": [
      ],
      "syntax": []
    },
    "syntax": []
  },
  "polyline": {
    "fields": [
    ],
    "syntax": []
  },
  "result": {
    "fields": [
    ],
    "syntax": []
  },
  "series": {
    "fields": [
    ],
    "syntax": [
      "export [method ]<functionName>([[series ]<paramType>] <paramName>[ = <defaultValue>])",
      "[method ]<functionName>([series <paramType> ]<paramName>[ = <defaultValue>])",
      "[var/varip ]series <variableType> <variableName> = <variableValue>"
    ]
  },
  "simple": {
    "fields": [
    ],
    "syntax": [
      "export [method ]<functionName>([[simple ]<paramType>] <paramName>[ = <defaultValue>])",
      "[method ]<functionName>([simple <paramType> ]<paramName>[ = <defaultValue>])",
      "[var/varip ]simple <variableType> <variableName> = <variableValue></variableValue>"
    ]
  },
  "str": {
    "format": {
      "fields": [
      ],
      "syntax": []
    },
    "tostring": {
      "fields": [
      ],
      "syntax": []
    }
  },
  "string": {
    "fields": [
    ],
    "syntax": []
  },
  "table": {
    "fields": [
    ],
    "new": {
      "fields": [
      ],
      "syntax": []
    },
    "syntax": []
  },
  "true": {
    "fields": [
    ],
    "syntax": []
  },
  "var": {
    "fields": [
    ],
    "syntax": []
  },
  "varip": {
    "fields": [
    ],
    "syntax": []
  }
} satisfies TypeMap;
export type Types = typeof types;

