// This file is automatically generated by scripts/extract-syntax-structures.ts.
// Do not edit this file directly.

import { defineVariable } from './schema';
import type { VariableMap } from './schema';

export const variables = {
  "ask": defineVariable({qualifier: "series", type: "float"}),
  "bar_index": defineVariable({qualifier: "series", type: "int"}),
  "barstate": {
    "isconfirmed": defineVariable({qualifier: "series", type: "bool"}),
    "isfirst": defineVariable({qualifier: "series", type: "bool"}),
    "ishistory": defineVariable({qualifier: "series", type: "bool"}),
    "islast": defineVariable({qualifier: "series", type: "bool"}),
    "islastconfirmedhistory": defineVariable({qualifier: "series", type: "bool"}),
    "isnew": defineVariable({qualifier: "series", type: "bool"}),
    "isrealtime": defineVariable({qualifier: "series", type: "bool"})
  },
  "bid": defineVariable({qualifier: "series", type: "float"}),
  "box": {
    "all": defineVariable({qualifier: null, type: "array<box>"})
  },
  "chart": {
    "bg_color": defineVariable({qualifier: "input", type: "color"}),
    "fg_color": defineVariable({qualifier: "input", type: "color"}),
    "is_heikinashi": defineVariable({qualifier: "simple", type: "bool"}),
    "is_kagi": defineVariable({qualifier: "simple", type: "bool"}),
    "is_linebreak": defineVariable({qualifier: "simple", type: "bool"}),
    "is_pnf": defineVariable({qualifier: "simple", type: "bool"}),
    "is_range": defineVariable({qualifier: "simple", type: "bool"}),
    "is_renko": defineVariable({qualifier: "simple", type: "bool"}),
    "is_standard": defineVariable({qualifier: "simple", type: "bool"}),
    "left_visible_bar_time": defineVariable({qualifier: "input", type: "int"}),
    "right_visible_bar_time": defineVariable({qualifier: "input", type: "int"})
  },
  "close": defineVariable({qualifier: "series", type: "float"}),
  "dayofmonth": defineVariable({qualifier: "series", type: "int"}),
  "dayofweek": defineVariable({qualifier: "series", type: "int"}),
  "dividends": {
    "future_amount": defineVariable({qualifier: "series", type: "float"}),
    "future_ex_date": defineVariable({qualifier: "series", type: "int"}),
    "future_pay_date": defineVariable({qualifier: "series", type: "int"})
  },
  "earnings": {
    "future_eps": defineVariable({qualifier: "series", type: "float"}),
    "future_period_end_time": defineVariable({qualifier: "series", type: "int"}),
    "future_revenue": defineVariable({qualifier: "series", type: "float"}),
    "future_time": defineVariable({qualifier: "series", type: "int"})
  },
  "high": defineVariable({qualifier: "series", type: "float"}),
  "hl2": defineVariable({qualifier: "series", type: "float"}),
  "hlc3": defineVariable({qualifier: "series", type: "float"}),
  "hlcc4": defineVariable({qualifier: "series", type: "float"}),
  "hour": defineVariable({qualifier: "series", type: "int"}),
  "label": {
    "all": defineVariable({qualifier: null, type: "array<label>"})
  },
  "last_bar_index": defineVariable({qualifier: "series", type: "int"}),
  "last_bar_time": defineVariable({qualifier: "series", type: "int"}),
  "line": {
    "all": defineVariable({qualifier: null, type: "array<line>"})
  },
  "linefill": {
    "all": defineVariable({qualifier: null, type: "array<linefill>"})
  },
  "low": defineVariable({qualifier: "series", type: "float"}),
  "minute": defineVariable({qualifier: "series", type: "int"}),
  "month": defineVariable({qualifier: "series", type: "int"}),
  "na": defineVariable({qualifier: "simple", type: "na"}),
  "ohlc4": defineVariable({qualifier: "series", type: "float"}),
  "open": defineVariable({qualifier: "series", type: "float"}),
  "polyline": {
    "all": defineVariable({qualifier: null, type: "array<polyline>"})
  },
  "second": defineVariable({qualifier: "series", type: "int"}),
  "session": {
    "isfirstbar": defineVariable({qualifier: "series", type: "bool"}),
    "isfirstbar_regular": defineVariable({qualifier: "series", type: "bool"}),
    "islastbar": defineVariable({qualifier: "series", type: "bool"}),
    "islastbar_regular": defineVariable({qualifier: "series", type: "bool"}),
    "ismarket": defineVariable({qualifier: "series", type: "bool"}),
    "ispostmarket": defineVariable({qualifier: "series", type: "bool"}),
    "ispremarket": defineVariable({qualifier: "series", type: "bool"})
  },
  "strategy": {
    "account_currency": defineVariable({qualifier: "simple", type: "string"}),
    "avg_losing_trade": defineVariable({qualifier: "series", type: "float"}),
    "avg_losing_trade_percent": defineVariable({qualifier: "series", type: "float"}),
    "avg_trade": defineVariable({qualifier: "series", type: "float"}),
    "avg_trade_percent": defineVariable({qualifier: "series", type: "float"}),
    "avg_winning_trade": defineVariable({qualifier: "series", type: "float"}),
    "avg_winning_trade_percent": defineVariable({qualifier: "series", type: "float"}),
    "closedtrades": defineVariable({qualifier: "series", type: "int"}),
    "equity": defineVariable({qualifier: "series", type: "float"}),
    "eventrades": defineVariable({qualifier: "series", type: "int"}),
    "grossloss": defineVariable({qualifier: "series", type: "float"}),
    "grossloss_percent": defineVariable({qualifier: "series", type: "float"}),
    "grossprofit": defineVariable({qualifier: "series", type: "float"}),
    "grossprofit_percent": defineVariable({qualifier: "series", type: "float"}),
    "initial_capital": defineVariable({qualifier: "series", type: "float"}),
    "losstrades": defineVariable({qualifier: "series", type: "int"}),
    "margin_liquidation_price": defineVariable({qualifier: "series", type: "float"}),
    "max_contracts_held_all": defineVariable({qualifier: "series", type: "float"}),
    "max_contracts_held_long": defineVariable({qualifier: "series", type: "float"}),
    "max_contracts_held_short": defineVariable({qualifier: "series", type: "float"}),
    "max_drawdown": defineVariable({qualifier: "series", type: "float"}),
    "max_drawdown_percent": defineVariable({qualifier: "series", type: "float"}),
    "max_runup": defineVariable({qualifier: "series", type: "float"}),
    "max_runup_percent": defineVariable({qualifier: "series", type: "float"}),
    "netprofit": defineVariable({qualifier: "series", type: "float"}),
    "netprofit_percent": defineVariable({qualifier: "series", type: "float"}),
    "openprofit": defineVariable({qualifier: "series", type: "float"}),
    "openprofit_percent": defineVariable({qualifier: "series", type: "float"}),
    "opentrades": defineVariable({qualifier: "series", type: "int"}),
    "position_avg_price": defineVariable({qualifier: "series", type: "float"}),
    "position_entry_name": defineVariable({qualifier: "series", type: "string"}),
    "position_size": defineVariable({qualifier: "series", type: "float"}),
    "wintrades": defineVariable({qualifier: "series", type: "int"})
  },
  "syminfo": {
    "basecurrency": defineVariable({qualifier: "simple", type: "string"}),
    "country": defineVariable({qualifier: "simple", type: "string"}),
    "currency": defineVariable({qualifier: "simple", type: "string"}),
    "current_contract": defineVariable({qualifier: "simple", type: "string"}),
    "description": defineVariable({qualifier: "simple", type: "string"}),
    "employees": defineVariable({qualifier: "simple", type: "int"}),
    "expiration_date": defineVariable({qualifier: "simple", type: "int"}),
    "industry": defineVariable({qualifier: "simple", type: "string"}),
    "main_tickerid": defineVariable({qualifier: "simple", type: "string"}),
    "mincontract": defineVariable({qualifier: "simple", type: "float"}),
    "minmove": defineVariable({qualifier: "simple", type: "int"}),
    "mintick": defineVariable({qualifier: "simple", type: "float"}),
    "pointvalue": defineVariable({qualifier: "simple", type: "float"}),
    "prefix": defineVariable({qualifier: "simple", type: "string"}),
    "pricescale": defineVariable({qualifier: "simple", type: "int"}),
    "recommendations_buy": defineVariable({qualifier: "series", type: "int"}),
    "recommendations_buy_strong": defineVariable({qualifier: "series", type: "int"}),
    "recommendations_date": defineVariable({qualifier: "series", type: "int"}),
    "recommendations_hold": defineVariable({qualifier: "series", type: "int"}),
    "recommendations_sell": defineVariable({qualifier: "series", type: "int"}),
    "recommendations_sell_strong": defineVariable({qualifier: "series", type: "int"}),
    "recommendations_total": defineVariable({qualifier: "series", type: "int"}),
    "root": defineVariable({qualifier: "simple", type: "string"}),
    "sector": defineVariable({qualifier: "simple", type: "string"}),
    "session": defineVariable({qualifier: "simple", type: "string"}),
    "shareholders": defineVariable({qualifier: "simple", type: "int"}),
    "shares_outstanding_float": defineVariable({qualifier: "simple", type: "float"}),
    "shares_outstanding_total": defineVariable({qualifier: "simple", type: "int"}),
    "target_price_average": defineVariable({qualifier: "series", type: "float"}),
    "target_price_date": defineVariable({qualifier: "series", type: "int"}),
    "target_price_estimates": defineVariable({qualifier: "series", type: "float"}),
    "target_price_high": defineVariable({qualifier: "series", type: "float"}),
    "target_price_low": defineVariable({qualifier: "series", type: "float"}),
    "target_price_median": defineVariable({qualifier: "series", type: "float"}),
    "ticker": defineVariable({qualifier: "simple", type: "string"}),
    "tickerid": defineVariable({qualifier: "simple", type: "string"}),
    "timezone": defineVariable({qualifier: "simple", type: "string"}),
    "type": defineVariable({qualifier: "simple", type: "string"}),
    "volumetype": defineVariable({qualifier: "simple", type: "string"})
  },
  "ta": {
    "accdist": defineVariable({qualifier: "series", type: "float"}),
    "iii": defineVariable({qualifier: "series", type: "float"}),
    "nvi": defineVariable({qualifier: "series", type: "float"}),
    "obv": defineVariable({qualifier: "series", type: "float"}),
    "pvi": defineVariable({qualifier: "series", type: "float"}),
    "pvt": defineVariable({qualifier: "series", type: "float"}),
    "tr": defineVariable({qualifier: "series", type: "float"}),
    "vwap": defineVariable({qualifier: "series", type: "float"}),
    "wad": defineVariable({qualifier: "series", type: "float"}),
    "wvad": defineVariable({qualifier: "series", type: "float"})
  },
  "table": {
    "all": defineVariable({qualifier: null, type: "array<table>"})
  },
  "time": defineVariable({qualifier: "series", type: "int"}),
  "time_close": defineVariable({qualifier: "series", type: "int"}),
  "time_tradingday": defineVariable({qualifier: "series", type: "int"}),
  "timeframe": {
    "isdaily": defineVariable({qualifier: "simple", type: "bool"}),
    "isdwm": defineVariable({qualifier: "simple", type: "bool"}),
    "isintraday": defineVariable({qualifier: "simple", type: "bool"}),
    "isminutes": defineVariable({qualifier: "simple", type: "bool"}),
    "ismonthly": defineVariable({qualifier: "simple", type: "bool"}),
    "isseconds": defineVariable({qualifier: "simple", type: "bool"}),
    "isticks": defineVariable({qualifier: "simple", type: "bool"}),
    "isweekly": defineVariable({qualifier: "simple", type: "bool"}),
    "main_period": defineVariable({qualifier: "simple", type: "string"}),
    "multiplier": defineVariable({qualifier: "simple", type: "int"}),
    "period": defineVariable({qualifier: "simple", type: "string"})
  },
  "timenow": defineVariable({qualifier: "series", type: "int"}),
  "volume": defineVariable({qualifier: "series", type: "float"}),
  "weekofyear": defineVariable({qualifier: "series", type: "int"}),
  "year": defineVariable({qualifier: "series", type: "int"})
} satisfies VariableMap;
export type Variables = typeof variables;

