/**
 * Centralized validation code identifiers to ensure consistency across modules.
 */

export const Codes = {
  // Ticker info
  TICKER_MODIFY: 'PSV6-TICKER-MODIFY',
  TICKER_SETTLEMENT_INFO: 'PSV6-TICKER-SETTLEMENT',
  TICKER_RENKO_INFO: 'PSV6-TICKER-RENKO',
  TICKER_PNF_INFO: 'PSV6-TICKER-PNF',
  TICKER_KAGI_INFO: 'PSV6-TICKER-KAGI',
  TICKER_HEIKIN_INFO: 'PSV6-TICKER-HEIKIN',
  TICKER_INHERIT_INFO: 'PSV6-TICKER-INHERIT',
  TICKER_NEW_INFO: 'PSV6-TICKER-NEW',

  // Ticker errors
  TICKER_MODIFY_UNKNOWN_PARAM: 'PSV6-TICKER-MODIFY-UNKNOWN-PARAM',
  TICKER_SETTLEMENT_VALUE: 'PSV6-TICKER-SETTLEMENT-VALUE',
  TICKER_ADJ_VALUE: 'PSV6-TICKER-ADJ-VALUE',
  TICKER_BACKADJ_VALUE: 'PSV6-TICKER-BACKADJ-VALUE',
  TICKER_SESSION_VALUE: 'PSV6-TICKER-SESSION-VALUE',

  TICKER_RENKO_SIZETYPE: 'PSV6-TICKER-RENKO-SIZETYPE',
  TICKER_RENKO_SIZE_TYPE: 'PSV6-TICKER-RENKO-SIZE-TYPE',
  TICKER_RENKO_WICKS_TYPE: 'PSV6-TICKER-RENKO-WICKS-TYPE',
  TICKER_RENKO_SOURCE: 'PSV6-TICKER-RENKO-SOURCE',

  TICKER_PNF_SOURCE: 'PSV6-TICKER-PNF-SOURCE',
  TICKER_PNF_SIZE_TYPE: 'PSV6-TICKER-PNF-SIZE-TYPE',
  TICKER_PNF_BOXSIZE: 'PSV6-TICKER-PNF-BOXSIZE',
  TICKER_PNF_REVERSAL_TYPE: 'PSV6-TICKER-PNF-REVERSAL-TYPE',

  TICKER_KAGI_PARAM_TYPE: 'PSV6-TICKER-KAGI-PARAM-TYPE',
  TICKER_KAGI_STYLE: 'PSV6-TICKER-KAGI-STYLE',

  // Generic categories (shared)
  SPECIALIZED_CONSTANT: 'PSV6-SPECIALIZED-CONSTANT',

  // Builtins/constants common codes
  DISPLAY_CONSTANT: 'PSV6-DISPLAY-CONSTANT',
  TIMEFRAME_CONSTANT: 'PSV6-TIMEFRAME-CONSTANT',
  EXTEND_CONSTANT: 'PSV6-EXTEND-CONSTANT',
  FORMAT_CONSTANT: 'PSV6-FORMAT-CONSTANT',
  CURRENCY_CONSTANT: 'PSV6-CURRENCY-CONSTANT',
  SCALE_CONSTANT: 'PSV6-SCALE-CONSTANT',
  ADJUSTMENT_CONSTANT: 'PSV6-ADJUSTMENT-CONSTANT',
  BACKADJUSTMENT_CONSTANT: 'PSV6-BACKADJUSTMENT-CONSTANT',

  BUILTIN_VARS_INFO: 'PSV6-BUILTIN-VARS-INFO',
  CURRENCY_USAGE: 'PSV6-CURRENCY-USAGE',
  DISPLAY_USAGE: 'PSV6-DISPLAY-USAGE',
  SCALE_USAGE: 'PSV6-SCALE-USAGE',
  ADJUSTMENT_USAGE: 'PSV6-ADJUSTMENT-USAGE',

  // Final constants
  STYLE_CONSTANT: 'PSV6-STYLE-CONSTANT',
  ORDER_CONSTANT: 'PSV6-ORDER-CONSTANT',
  POSITION_CONSTANT: 'PSV6-POSITION-CONSTANT',
  FINAL_CONSTANTS_INFO: 'PSV6-FINAL-CONSTANTS-INFO',
  MATH_CONSTANTS_USAGE: 'PSV6-MATH-CONSTANTS-USAGE',
  CONST_POSITION_INVALID: 'PSV6-CONST-POSITION',
  CONST_LOCATION_INVALID: 'PSV6-CONST-LOCATION',
  CONST_XYLOC_INVALID: 'PSV6-CONST-LOC',
  CONST_TEXT_ALIGN_INVALID: 'PSV6-CONST-TEXT-ALIGN',
  CONST_SIZE_INVALID: 'PSV6-CONST-SIZE',
  CONST_EXTEND_INVALID: 'PSV6-CONST-EXTEND',
  CONST_LINE_STYLE_INVALID: 'PSV6-CONST-LINE-STYLE',
  CONST_LABEL_STYLE_INVALID: 'PSV6-CONST-LABEL-STYLE',
  CONST_PLOT_STYLE_INVALID: 'PSV6-CONST-PLOT-STYLE',
  CONST_SHAPE_INVALID: 'PSV6-CONST-SHAPE',
  CONST_ORDER_INVALID: 'PSV6-CONST-ORDER',
  CONST_DISPLAY_INVALID: 'PSV6-CONST-DISPLAY',

  // Additional constants and syminfo
  ADDITIONAL_CONSTANT: 'PSV6-ADDITIONAL-CONSTANT',
  SYMINFO_ADDITIONAL: 'PSV6-SYMINFO-ADDITIONAL',

  // Strategy function codes
  STRATEGY_FUNCTION_PARAM: 'PSV6-STRATEGY-FUNCTION-PARAM',
  STRATEGY_FUNCTION_UNKNOWN: 'PSV6-STRATEGY-FUNCTION-UNKNOWN',
  STRATEGY_INVALID: 'PSV6-STRATEGY-INVALID',
  STRATEGY_CONSTANT_AS_FUNCTION: 'PSV6-STRATEGY-CONSTANT-AS-FUNCTION',
  STRATEGY_ALLOW_ENTRY_PARAMS: 'PSV6-STRATEGY-ALLOW-ENTRY-PARAMS',
  STRATEGY_MAX_POSITION_SIZE: 'PSV6-STRATEGY-MAX-POSITION-SIZE',
  STRATEGY_MAX_DRAWDOWN_VALUE: 'PSV6-STRATEGY-MAX-DRAWDOWN-VALUE',
  STRATEGY_MAX_ORDERS_VALUE: 'PSV6-STRATEGY-MAX-ORDERS-VALUE',

  // Core syntax codes
  NUMERIC_CONDITION: 'PSV6-001',
  MIXED_INDENTATION: 'PSV6-STYLE-MIXED-INDENTATION',
  PERFORMANCE_ALERT_CONSOLIDATE: 'PSV6-PERF-ALERT-CONSOLIDATE',
  TERNARY_TYPE: 'PSV6-TERNARY-TYPE',
  TYPE_FLOW: 'PSV6-TYPE-FLOW',
  FUNCTION_NAMESPACE: 'PSV6-FUNCTION-NAMESPACE',

  // Legacy codes for compatibility
  INVALID_OPERATOR: 'PSO01',
  ASSIGNMENT_IN_CONDITION: 'PSO02',
  MIXED_TABS_SPACES: 'PSI02',
  CURLY_BRACES: 'PS011',
  
  // Syntax pre-check codes
  SYNTAX_CLOSING_PAREN: 'PSV6-SYNTAX-CLOSING-PAREN',
  SYNTAX_ERROR: 'PSV6-SYNTAX-ERROR',
  SYNTAX_MISSING_PARAM: 'PSV6-SYNTAX-MISSING-PARAM',
  
  // TA Function codes
  TA_FUNCTION_PARAM: 'PSV6-TA-FUNCTION-PARAM',
  TA_FUNCTION_UNKNOWN: 'PSV6-TA-FUNCTION-UNKNOWN',
  TA_INVALID: 'PSV6-TA-INVALID',
  TA_PERF_NESTED: 'PSV6-TA-PERF-NESTED',
  TA_PERF_MANY: 'PSV6-TA-PERF-MANY',
  TA_PERF_LOOP: 'PSV6-TA-PERF-LOOP',
  TA_CACHE_SUGGESTION: 'PSV6-TA-CACHE-SUGGESTION',
  TA_PARAM_SUGGESTION: 'PSV6-TA-PARAM-SUGGESTION',
  TA_COMBINATION_SUGGESTION: 'PSV6-TA-COMBINATION-SUGGESTION',
  
  // String function codes
  STR_UNKNOWN_FUNCTION: 'PSV6-STR-UNKNOWN-FUNCTION',
  STR_FORMAT_INVALID: 'PSV6-STR-FORMAT-INVALID',
  STR_FORMAT_SUGGESTION: 'PSV6-STR-FORMAT-SUGGESTION',
  STR_FORMAT_TIME_INVALID: 'PSV6-STR-FORMAT-TIME-INVALID',
  STR_CONVERSION_INVALID: 'PSV6-STR-CONVERSION-INVALID',
  STR_CACHE_SUGGESTION: 'PSV6-STR-CACHE-SUGGESTION',
  STR_LITERAL_SUGGESTION: 'PSV6-STR-LITERAL-SUGGESTION',
  STR_MATCH_INVALID_REGEX: 'PSV6-STR-MATCH-INVALID-REGEX',
  STR_PERF_COMPLEX: 'PSV6-STR-PERF-COMPLEX',
  STR_PERF_LOOP: 'PSV6-STR-PERF-LOOP',
  STR_PERF_CONCAT: 'PSV6-STR-PERF-CONCAT',
  STR_SUBSTRING_NEGATIVE_INDEX: 'PSV6-STR-SUBSTRING-NEGATIVE-INDEX',
  STR_SUBSTRING_INVALID_RANGE: 'PSV6-STR-SUBSTRING-INVALID-RANGE',
  STR_REPEAT_NEGATIVE_COUNT: 'PSV6-STR-REPEAT-NEGATIVE-COUNT',
  STR_REPEAT_LARGE_COUNT: 'PSV6-STR-REPEAT-LARGE-COUNT',
  STR_TONUMBER_NA: 'PSV6-STR-TONUMBER-NA',
  
  // Generic function codes
  FUNCTION_PARAM_TYPE: 'PSV6-FUNCTION-PARAM-TYPE',
  FUNCTION_PARAM_COUNT: 'PSV6-FUNCTION-PARAM-COUNT',
  FUNCTION_RETURN_TYPE: 'PSV6-FUNCTION-RETURN-TYPE',
  FUNCTION_UNKNOWN: 'PSV6-FUNCTION-UNKNOWN',
  FUNCTION_CALL_PARAM_COUNT: 'PSV6-FUNCTION-CALL-PARAM-COUNT',
  METHOD_INVALID: 'PSV6-METHOD-INVALID',
  
  // Input function codes
  INPUT_DEFAULT_TYPE: 'PSV6-INPUT-DEFAULT-TYPE',
  INPUT_DEFVAL_TYPE: 'PSV6-INPUT-DEFVAL-TYPE',
  
  // Type function codes
  TYPE_FUNCTION_PARAM_MISMATCH: 'PSV6-TYPE-FUNCTION-PARAM-MISMATCH',
  
  // Migration codes
  MIG_SYNTAX: 'PSV6-MIG-SYNTAX',
  
  
  // Request function codes
  REQUEST_UNKNOWN: 'PSV6-REQUEST-UNKNOWN',
  REQUEST_PARAMS: 'PSV6-REQUEST-PARAMS',
  REQUEST_SYMBOL_EMPTY: 'PSV6-REQUEST-SYMBOL-EMPTY',
  REQUEST_SYMBOL_FORMAT: 'PSV6-REQUEST-SYMBOL-FORMAT',
  REQUEST_SYMBOL_LENGTH: 'PSV6-REQUEST-SYMBOL-LENGTH',
  REQUEST_SYMBOL_UNKNOWN: 'PSV6-REQUEST-SYMBOL-UNKNOWN',
  REQUEST_SYMBOL_CHARS: 'PSV6-REQUEST-SYMBOL-CHARS',
  REQUEST_CURRENCY_CODE: 'PSV6-REQUEST-CURRENCY-CODE',
  REQUEST_CURRENCY_IGNORE: 'PSV6-REQUEST-CURRENCY-IGNORE',
  REQUEST_CURRENCY_RATE_PARAMS: 'PSV6-REQUEST-CURRENCY-RATE-PARAMS',
  REQUEST_DIVIDENDS_FIELD: 'PSV6-REQUEST-DIVIDENDS-FIELD',
  REQUEST_DIVIDENDS_PARAMS: 'PSV6-REQUEST-DIVIDENDS-PARAMS',
  REQUEST_EARNINGS_FIELD: 'PSV6-REQUEST-EARNINGS-FIELD',
  REQUEST_EARNINGS_PARAMS: 'PSV6-REQUEST-EARNINGS-PARAMS',
  REQUEST_SPLITS_FIELD: 'PSV6-REQUEST-SPLITS-FIELD',
  REQUEST_SPLITS_PARAMS: 'PSV6-REQUEST-SPLITS-PARAMS',
  REQUEST_FINANCIAL_FIELD: 'PSV6-REQUEST-FINANCIAL-FIELD',
  REQUEST_FINANCIAL_ID: 'PSV6-REQUEST-FINANCIAL-ID',
  REQUEST_FINANCIAL_PARAMS: 'PSV6-REQUEST-FINANCIAL-PARAMS',
  REQUEST_FINANCIAL_PERIOD: 'PSV6-REQUEST-FINANCIAL-PERIOD',
  REQUEST_ECONOMIC_COUNTRY: 'PSV6-REQUEST-ECONOMIC-COUNTRY',
  REQUEST_ECONOMIC_FIELD: 'PSV6-REQUEST-ECONOMIC-FIELD',
  REQUEST_ECONOMIC_PARAMS: 'PSV6-REQUEST-ECONOMIC-PARAMS',
  REQUEST_EXCHANGE_UNKNOWN: 'PSV6-REQUEST-EXCHANGE-UNKNOWN',
  REQUEST_SECURITY_PARAMS: 'PSV6-REQUEST-SECURITY-PARAMS',
  REQUEST_SECURITY_LOWER_TF_PARAMS: 'PSV6-REQUEST-SECURITY-LOWER-TF-PARAMS',
  REQUEST_QUANDL_PARAMS: 'PSV6-REQUEST-QUANDL-PARAMS',
  REQUEST_QUANDL_FORMAT: 'PSV6-REQUEST-QUANDL-FORMAT',
  REQUEST_SEED_PARAMS: 'PSV6-REQUEST-SEED-PARAMS',
  REQUEST_SEED_SOURCE: 'PSV6-REQUEST-SEED-SOURCE',
  REQUEST_SEED_SYMBOL: 'PSV6-REQUEST-SEED-SYMBOL',
  REQUEST_SEED_EXPRESSION: 'PSV6-REQUEST-SEED-EXPRESSION',
  REQUEST_SEED_EXT: 'PSV6-REQUEST-SEED-EXT',
  REQUEST_SEED_CALC_BARS: 'PSV6-REQUEST-SEED-CALC-BARS',
  REQUEST_SEED_CALC_BARS_DYNAMIC: 'PSV6-REQUEST-SEED-CALC-BARS-DYNAMIC',
  REQUEST_DYNAMIC_SYMBOL: 'PSV6-REQUEST-DYNAMIC-SYMBOL',
  REQUEST_DYNAMIC_TIMEFRAME: 'PSV6-REQUEST-DYNAMIC-TIMEFRAME',
  REQUEST_DYNAMIC_CONDITIONAL: 'PSV6-REQUEST-DYNAMIC-CONDITIONAL',
  REQUEST_DYNAMIC_LOOP: 'PSV6-REQUEST-DYNAMIC-LOOP',
  REQUEST_GAPS_INVALID: 'PSV6-REQUEST-GAPS-INVALID',
  REQUEST_GAPS_DYNAMIC: 'PSV6-REQUEST-GAPS-DYNAMIC',
  REQUEST_GAPS_BARMERGE: 'PSV6-REQUEST-GAPS-BARMERGE',
  REQUEST_LOOKAHEAD_INVALID: 'PSV6-REQUEST-LOOKAHEAD-INVALID',
  REQUEST_LOOKAHEAD_DYNAMIC: 'PSV6-REQUEST-LOOKAHEAD-DYNAMIC',
  REQUEST_PERF_COUNT: 'PSV6-REQUEST-PERF-COUNT',
  REQUEST_PERF_LOOP: 'PSV6-REQUEST-PERF-LOOP',
  REQUEST_PERFORMANCE_EXPENSIVE: 'PSV6-REQUEST-PERFORMANCE-EXPENSIVE',
  REQUEST_PERFORMANCE_MULTIPLE: 'PSV6-REQUEST-PERFORMANCE-MULTIPLE',
  REQUEST_LIMIT_APPROACHING: 'PSV6-REQUEST-LIMIT-APPROACHING',
  REQUEST_LIMIT_NEAR: 'PSV6-REQUEST-LIMIT-NEAR',
  
  // Drawing function codes
  DRAWING_INVALID: 'PSV6-DRAWING-INVALID',
  DRAWING_TOO_MANY: 'PSV6-DRAWING-TOO-MANY',
  DRAWING_IN_LOOP: 'PSV6-DRAWING-IN-LOOP',
  DRAWING_COMPLEX_EXPRESSION: 'PSV6-DRAWING-COMPLEX-EXPRESSION',
  DRAWING_CLEANUP_SUGGESTION: 'PSV6-DRAWING-CLEANUP-SUGGESTION',
  DRAWING_NAMING_SUGGESTION: 'PSV6-DRAWING-NAMING-SUGGESTION',
  DRAWING_POSITION_SUGGESTION: 'PSV6-DRAWING-POSITION-SUGGESTION',
  DRAWING_STYLE_SUGGESTION: 'PSV6-DRAWING-STYLE-SUGGESTION',
  
  // Line function codes
  LINE_UNKNOWN_FUNCTION: 'PSV6-LINE-UNKNOWN-FUNCTION',
  LINE_COLOR_TYPE: 'PSV6-LINE-COLOR-TYPE',
  LINE_COORDINATE_TYPE: 'PSV6-LINE-COORDINATE-TYPE',
  LINE_STYLE_TYPE: 'PSV6-LINE-STYLE-TYPE',
  LINE_WIDTH_RANGE: 'PSV6-LINE-WIDTH-RANGE',
  
  // Label function codes
  LABEL_UNKNOWN_FUNCTION: 'PSV6-LABEL-UNKNOWN-FUNCTION',
  LABEL_COORDINATE_TYPE: 'PSV6-LABEL-COORDINATE-TYPE',
  LABEL_TEXT_TYPE: 'PSV6-LABEL-TEXT-TYPE',
  LABEL_TEXT_STYLE: 'PSV6-LABEL-TEXT-STYLE',
  LABEL_TEXT_SIZE: 'PSV6-LABEL-TEXT-SIZE',
  
  // Box function codes
  BOX_UNKNOWN_FUNCTION: 'PSV6-BOX-UNKNOWN-FUNCTION',
  BOX_COLOR_TYPE: 'PSV6-BOX-COLOR-TYPE',
  BOX_COORDINATE_TYPE: 'PSV6-BOX-COORDINATE-TYPE',
  BOX_WIDTH_TYPE: 'PSV6-BOX-WIDTH-TYPE',
  
  // Table function codes
  TABLE_UNKNOWN_FUNCTION: 'PSV6-TABLE-UNKNOWN-FUNCTION',
  TABLE_COLOR_TYPE: 'PSV6-TABLE-COLOR-TYPE',
  TABLE_DIMENSION_TYPE: 'PSV6-TABLE-DIMENSION-TYPE',
  TABLE_POSITION_TYPE: 'PSV6-TABLE-POSITION-TYPE',
  TABLE_CELL_COLOR_TYPE: 'PSV6-TABLE-CELL-COLOR-TYPE',
  TABLE_CELL_TEXT_TYPE: 'PSV6-TABLE-CELL-TEXT-TYPE',
  TABLE_CELL_TEXT_SIZE: 'PSV6-TABLE-CELL-TEXT-SIZE',
  TABLE_FRAME_WIDTH: 'PSV6-TABLE-FRAME-WIDTH',
  TABLE_BORDER_WIDTH: 'PSV6-TABLE-BORDER-WIDTH',
  
  // Map codes
  MAP_DECLARATION: 'PSV6-MAP-DECLARATION',
  MAP_OPERATION_NON_MAP: 'PSV6-MAP-OPERATION-NON-MAP',
  MAP_METHOD_PARAMS: 'PSV6-MAP-METHOD-PARAMS',
  MAP_TYPE_MISMATCH: 'PSV6-MAP-TYPE-MISMATCH',
  MAP_VALUE_TYPE_MISMATCH: 'PSV6-MAP-VALUE-TYPE-MISMATCH',
  
  // Syminfo codes
  SYMINFO_USAGE: 'PSV6-SYMINFO-USAGE',
  SYMINFO_COMPANY: 'PSV6-SYMINFO-COMPANY',
  SYMINFO_RECOMMENDATIONS: 'PSV6-SYMINFO-RECOMMENDATIONS',
  SYMINFO_TARGET_PRICE: 'PSV6-SYMINFO-TARGET-PRICE',
  FINANCIAL_DATA_USAGE: 'PSV6-FINANCIAL-DATA-USAGE',
  CONSTANTS_USAGE: 'PSV6-CONSTANTS-USAGE',
  
  // Style and quality codes
  STYLE_NAMING: 'PSV6-STYLE-NAMING',
  STYLE_MAGIC: 'PSV6-STYLE-MAGIC',
  STYLE_COMPLEXITY: 'PSV6-STYLE-COMPLEXITY',
  STYLE_FUNCTION_LENGTH: 'PSV6-STYLE-FUNCTION-LENGTH',
  STYLE_ORGANIZATION: 'PSV6-STYLE-ORGANIZATION',
  STYLE_MIXED_SECTIONS: 'PSV6-STYLE-MIXED-SECTIONS',
  STYLE_INPUT_PLACEMENT: 'PSV6-STYLE-INPUT-PLACEMENT',
  
  // Varip codes
  VARIP_SYNTAX: 'PSV6-VARIP-SYNTAX',
  VARIP_INITIAL_VALUE: 'PSV6-VARIP-INITIAL-VALUE',
  VARIP_LITERAL_INIT: 'PSV6-VARIP-LITERAL-INIT',
  VARIP_TYPE_INFERENCE: 'PSV6-VARIP-TYPE-INFERENCE',
  VARIP_NAMING: 'PSV6-VARIP-NAMING',
  VARIP_NAMING_SUGGESTION: 'PSV6-VARIP-NAMING-SUGGESTION',
  VARIP_SCOPE_FUNCTION: 'PSV6-VARIP-SCOPE-FUNCTION',
  VARIP_SCOPE_LOOP: 'PSV6-VARIP-SCOPE-LOOP',
  VARIP_ASSIGNMENT: 'PSV6-VARIP-ASSIGNMENT',
  VARIP_BARSTATE: 'PSV6-VARIP-BARSTATE',
  VARIP_PERFORMANCE: 'PSV6-VARIP-PERFORMANCE',
  VARIP_STRATEGY: 'PSV6-VARIP-STRATEGY',
  
  // Enum codes
  ENUM_NAMING_SUGGESTION: 'PSV6-ENUM-NAMING-SUGGESTION',
  ENUM_EMPTY: 'PSV6-ENUM-EMPTY',
  ENUM_INVALID_VALUE_NAME: 'PSV6-ENUM-INVALID-VALUE-NAME',
  ENUM_DUPLICATE_VALUE: 'PSV6-ENUM-DUPLICATE-VALUE',
  ENUM_VALUE_NAMING_SUGGESTION: 'PSV6-ENUM-VALUE-NAMING-SUGGESTION',
  ENUM_UNDEFINED_TYPE: 'PSV6-ENUM-UNDEFINED-TYPE',
  ENUM_UNDEFINED_VALUE: 'PSV6-ENUM-UNDEFINED-VALUE',
  ENUM_TYPE_MISMATCH: 'PSV6-ENUM-TYPE-MISMATCH',
  ENUM_COMPARISON_TYPE_MISMATCH: 'PSV6-ENUM-COMPARISON-TYPE-MISMATCH',
  ENUM_FUNCTION_TYPE_MISMATCH: 'PSV6-ENUM-FUNCTION-TYPE-MISMATCH',
  ENUM_SWITCH_CASE_TYPE_MISMATCH: 'PSV6-ENUM-SWITCH-CASE-TYPE-MISMATCH',
  
  // Linefill codes
  LINEFILL_PERF_LOOP: 'PSV6-LINEFILL-PERF-LOOP',
  LINEFILL_PERF_COMPLEX: 'PSV6-LINEFILL-PERF-COMPLEX',
  LINEFILL_UNKNOWN_FUNCTION: 'PSV6-LINEFILL-UNKNOWN-FUNCTION',
  LINEFILL_TRANSPARENCY_SUGGESTION: 'PSV6-LINEFILL-TRANSPARENCY-SUGGESTION',
  LINEFILL_PERF_MANY: 'PSV6-LINEFILL-PERF-MANY',
  LINEFILL_CACHE_SUGGESTION: 'PSV6-LINEFILL-CACHE-SUGGESTION',
  LINEFILL_CLEANUP_SUGGESTION: 'PSV6-LINEFILL-CLEANUP-SUGGESTION',

  // Math codes
  MATH_FUNCTION_UNKNOWN: 'PSV6-MATH-FUNCTION-UNKNOWN',
  MATH_FUNCTION_PARAM: 'PSV6-MATH-FUNCTION-PARAM',
  MATH_PARAM_COUNT: 'PSV6-MATH-PARAM-COUNT',
  MATH_INVALID: 'PSV6-MATH-INVALID',
  MATH_PERF_LOOP: 'PSV6-MATH-PERF-LOOP',
  MATH_PERF_NESTED: 'PSV6-MATH-PERF-NESTED',
  MATH_PERF_MANY: 'PSV6-MATH-PERF-MANY',
  MATH_COMPLEXITY: 'PSV6-MATH-COMPLEXITY',
  MATH_CACHE_SUGGESTION: 'PSV6-MATH-CACHE-SUGGESTION',
  MATH_PARAM_SUGGESTION: 'PSV6-MATH-PARAM-SUGGESTION',
  MATH_COMBINATION_SUGGESTION: 'PSV6-MATH-COMBINATION-SUGGESTION',

  // Strategy codes
  STRATEGY_PERF_MANY_CALLS: 'PSV6-STRATEGY-PERF-MANY-CALLS',
  STRATEGY_PERF_LOOP: 'PSV6-STRATEGY-PERF-LOOP',
  STRATEGY_PERF_NESTED: 'PSV6-STRATEGY-PERF-NESTED',

  // Quality codes
  QUALITY_COMPLEXITY: 'PSV6-QUALITY-COMPLEXITY',
  QUALITY_DEPTH: 'PSV6-QUALITY-DEPTH',
  QUALITY_LENGTH: 'PSV6-QUALITY-LENGTH',
  STRATEGY_POSITION_SIZE_SUGGESTION: 'PSV6-STRATEGY-POSITION-SIZE-SUGGESTION',
  STRATEGY_RISK_SUGGESTION: 'PSV6-STRATEGY-RISK-SUGGESTION',
  STRATEGY_EQUITY_SUGGESTION: 'PSV6-STRATEGY-EQUITY-SUGGESTION',
  STRATEGY_RISK_MANAGEMENT: 'PSV6-STRATEGY-RISK-MANAGEMENT',
  STRATEGY_POSITION_CONTROL: 'PSV6-STRATEGY-POSITION-CONTROL',
  STRATEGY_DRAWDOWN_PROTECTION: 'PSV6-STRATEGY-DRAWDOWN-PROTECTION',
  
  // Legacy codes
  PSDUP01: 'PSDUP01',
  
  // Module error
  MODULE_ERROR: 'MODULE-ERROR'
} as const;

export type Code = (typeof Codes)[keyof typeof Codes];
