import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface ScrapedEntry {
  id: string;
  name: string;
  description: string;
  type_info: string;
  category: string;
  type: 'variable' | 'function' | 'constant' | 'type' | 'annotation' | 'operator' | 'keyword';
  source_url: string;
  scraped_at: string;
  remarks?: string;
  see_also?: Array<{ name: string; reference: string }>;
  example?: string;
  returns?: string;
  syntax?: string;
  'syntax_&_overloads'?: string;
  parameters?: Array<{ text: string }>;
  fields?: string;
}

interface ParsedTypeInfo {
  qualifier: string | null;
  type: string;
}

function parseTypeInfo(typeInfo: string): ParsedTypeInfo {
  if (!typeInfo || typeInfo === 'undefined') {
    return { qualifier: null, type: 'void' };
  }
  
  const parts = typeInfo.trim().split(/\s+/);
  
  if (parts.length === 1) {
    return { qualifier: null, type: parts[0] };
  }
  
  const qualifier = parts[0];
  const type = parts.slice(1).join(' ');
  
  return { qualifier, type };
}

function sanitizeName(name: string): string {
  // Remove () from function names
  return name.replace(/\(\)$/, '');
}

function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

function generateVariablesFile(entries: ScrapedEntry[]): string {
  const variables = entries.filter(e => e.type === 'variable');
  
  let code = `// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: ${new Date().toISOString()}

export interface PineVariableMetadata {
  readonly name: string;
  readonly qualifier: string | null;
  readonly type: string;
  readonly description: string;
  readonly remarks?: string;
  readonly example?: string;
  readonly seeAlso?: ReadonlyArray<{ name: string; reference: string }>;
}

`;

  // Build nested structure
  const varTree: any = {};
  
  variables.forEach(v => {
    const cleanName = sanitizeName(v.name);
    const parts = cleanName.split('.');
    const { qualifier, type } = parseTypeInfo(v.type_info);
    
    const metadata: any = {
      name: cleanName,
      qualifier,
      type,
      description: v.description,
    };
    
    if (v.remarks) metadata.remarks = v.remarks;
    if (v.example) metadata.example = v.example;
    if (v.see_also && v.see_also.length > 0) metadata.seeAlso = v.see_also;
    
    let current = varTree;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (i === parts.length - 1) {
        current[part] = metadata;
      } else {
        if (!current[part] || typeof current[part] !== 'object' || current[part].name) {
          current[part] = {};
        }
        current = current[part];
      }
    }
  });
  
  code += 'export const variables: Record<string, PineVariableMetadata | any> = ';
  code += JSON.stringify(varTree, null, 2);
  code += ' as const;\n';
  
  return code;
}

function generateFunctionsFile(entries: ScrapedEntry[]): string {
  const functions = entries.filter(e => e.type === 'function');
  
  let code = `// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: ${new Date().toISOString()}

export interface PineFunctionParameter {
  readonly text: string;
}

export interface PineFunctionMetadata {
  readonly name: string;
  readonly description: string;
  readonly syntax?: string;
  readonly parameters?: ReadonlyArray<PineFunctionParameter>;
  readonly returns?: string;
  readonly example?: string;
  readonly remarks?: string;
  readonly seeAlso?: ReadonlyArray<{ name: string; reference: string }>;
}

`;

  // Build nested structure
  const funcTree: any = {};
  
  functions.forEach(f => {
    const cleanName = sanitizeName(f.name);
    const parts = cleanName.split('.');
    
    const metadata: any = {
      name: cleanName,
      description: f.description,
    };
    
    if (f.syntax) metadata.syntax = f.syntax;
    if (f['syntax_&_overloads']) metadata.syntax = f['syntax_&_overloads'];
    if (f.parameters && f.parameters.length > 0) metadata.parameters = f.parameters;
    if (f.returns) metadata.returns = f.returns;
    if (f.example) metadata.example = f.example;
    if (f.remarks) metadata.remarks = f.remarks;
    if (f.see_also && f.see_also.length > 0) metadata.seeAlso = f.see_also;
    
    let current = funcTree;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (i === parts.length - 1) {
        current[part] = metadata;
      } else {
        if (!current[part] || typeof current[part] !== 'object' || current[part].name) {
          current[part] = {};
        }
        current = current[part];
      }
    }
  });
  
  code += 'export const functions: Record<string, PineFunctionMetadata | any> = ';
  code += JSON.stringify(funcTree, null, 2);
  code += ' as const;\n';
  
  return code;
}

function generateConstantsFile(entries: ScrapedEntry[]): string {
  const constants = entries.filter(e => e.type === 'constant');
  
  let code = `// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: ${new Date().toISOString()}

export interface PineConstantMetadata {
  readonly name: string;
  readonly qualifier: string | null;
  readonly type: string;
  readonly description: string;
  readonly remarks?: string;
  readonly seeAlso?: ReadonlyArray<{ name: string; reference: string }>;
}

`;

  // Build nested structure
  const constTree: any = {};
  
  constants.forEach(c => {
    const cleanName = sanitizeName(c.name);
    const parts = cleanName.split('.');
    const { qualifier, type } = parseTypeInfo(c.type_info);
    
    const metadata: any = {
      name: cleanName,
      qualifier,
      type,
      description: c.description,
    };
    
    if (c.remarks) metadata.remarks = c.remarks;
    if (c.see_also && c.see_also.length > 0) metadata.seeAlso = c.see_also;
    
    let current = constTree;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (i === parts.length - 1) {
        current[part] = metadata;
      } else {
        if (!current[part] || typeof current[part] !== 'object' || current[part].name) {
          current[part] = {};
        }
        current = current[part];
      }
    }
  });
  
  code += 'export const constants: Record<string, PineConstantMetadata | any> = ';
  code += JSON.stringify(constTree, null, 2);
  code += ' as const;\n';
  
  return code;
}

function generateKeywordsFile(entries: ScrapedEntry[]): string {
  const keywords = entries.filter(e => e.type === 'keyword');
  
  let code = `// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: ${new Date().toISOString()}

export interface PineKeywordMetadata {
  readonly name: string;
  readonly description: string;
  readonly syntax?: string;
  readonly example?: string;
  readonly remarks?: string;
  readonly returns?: string;
  readonly seeAlso?: ReadonlyArray<{ name: string; reference: string }>;
}

`;

  const keywordMap: any = {};
  
  keywords.forEach(k => {
    const cleanName = sanitizeName(k.name);
    
    const metadata: any = {
      name: cleanName,
      description: k.description,
    };
    
    if (k.syntax) metadata.syntax = k.syntax;
    if (k.example) metadata.example = k.example;
    if (k.remarks) metadata.remarks = k.remarks;
    if (k.returns) metadata.returns = k.returns;
    if (k.see_also && k.see_also.length > 0) metadata.seeAlso = k.see_also;
    
    keywordMap[cleanName] = metadata;
  });
  
  code += 'export const keywords: Record<string, PineKeywordMetadata> = ';
  code += JSON.stringify(keywordMap, null, 2);
  code += ' as const;\n';
  
  return code;
}

function generateOperatorsFile(entries: ScrapedEntry[]): string {
  const operators = entries.filter(e => e.type === 'operator');
  
  let code = `// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: ${new Date().toISOString()}

export interface PineOperatorMetadata {
  readonly name: string;
  readonly description: string;
  readonly syntax: string;
  readonly example?: string;
  readonly remarks?: string;
  readonly returns?: string;
}

`;

  const opMap: any = {};
  
  operators.forEach(op => {
    const cleanName = sanitizeName(op.name);
    
    const metadata: any = {
      name: cleanName,
      description: op.description,
      syntax: op.syntax || '',
    };
    
    if (op.example) metadata.example = op.example;
    if (op.remarks) metadata.remarks = op.remarks;
    if (op.returns) metadata.returns = op.returns;
    
    opMap[cleanName] = metadata;
  });
  
  code += 'export const operators: Record<string, PineOperatorMetadata> = ';
  code += JSON.stringify(opMap, null, 2);
  code += ' as const;\n';
  
  return code;
}

function generateTypesFile(entries: ScrapedEntry[]): string {
  const types = entries.filter(e => e.type === 'type');
  
  let code = `// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: ${new Date().toISOString()}

export interface PineTypeMetadata {
  readonly name: string;
  readonly description: string;
  readonly fields?: string;
  readonly example?: string;
  readonly remarks?: string;
  readonly seeAlso?: ReadonlyArray<{ name: string; reference: string }>;
}

`;

  const typeMap: any = {};
  
  types.forEach(t => {
    const cleanName = sanitizeName(t.name);
    
    const metadata: any = {
      name: cleanName,
      description: t.description,
    };
    
    if (t.fields) metadata.fields = t.fields;
    if (t.example) metadata.example = t.example;
    if (t.remarks) metadata.remarks = t.remarks;
    if (t.see_also && t.see_also.length > 0) metadata.seeAlso = t.see_also;
    
    typeMap[cleanName] = metadata;
  });
  
  code += 'export const types: Record<string, PineTypeMetadata> = ';
  code += JSON.stringify(typeMap, null, 2);
  code += ' as const;\n';
  
  return code;
}

function generateAnnotationsFile(entries: ScrapedEntry[]): string {
  const annotations = entries.filter(e => e.type === 'annotation');
  
  let code = `// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: ${new Date().toISOString()}

export interface PineAnnotationMetadata {
  readonly name: string;
  readonly description: string;
  readonly example?: string;
  readonly remarks?: string;
}

`;

  const annMap: any = {};
  
  annotations.forEach(a => {
    const cleanName = sanitizeName(a.name);
    
    const metadata: any = {
      name: cleanName,
      description: a.description,
    };
    
    if (a.example) metadata.example = a.example;
    if (a.remarks) metadata.remarks = a.remarks;
    
    annMap[cleanName] = metadata;
  });
  
  code += 'export const annotations: Record<string, PineAnnotationMetadata> = ';
  code += JSON.stringify(annMap, null, 2);
  code += ' as const;\n';
  
  return code;
}

function generateIndexFile(): string {
  return `// This file is automatically generated from scraped Pine Script v6 documentation.
// Do not edit this file directly.
// Generated at: ${new Date().toISOString()}

export * from './variables';
export * from './functions';
export * from './constants';
export * from './keywords';
export * from './operators';
export * from './types';
export * from './annotations';

import { variables } from './variables';
import { functions } from './functions';
import { constants } from './constants';
import { keywords } from './keywords';
import { operators } from './operators';
import { types } from './types';
import { annotations } from './annotations';

export const pineScriptDocumentation = {
  variables,
  functions,
  constants,
  keywords,
  operators,
  types,
  annotations,
} as const;

export type PineScriptDocumentation = typeof pineScriptDocumentation;
`;
}

function generateReadme(): string {
  return `# Enhanced Pine Script Structures

This directory contains TypeScript structures automatically generated from scraped Pine Script v6 documentation.

## Generation

These files are generated by \`scripts/generate-enhanced-structures.ts\` from \`PineScriptContext/pinescript_reference.jsonl\`.

## Structure

Each file contains rich metadata including:
- **Variables**: name, qualifier, type, description, remarks, examples, see also references
- **Functions**: name, description, syntax, parameters, returns, examples, remarks, see also references
- **Constants**: name, qualifier, type, description, remarks, see also references
- **Keywords**: name, description, syntax, examples, remarks, returns, see also references
- **Operators**: name, description, syntax, examples, remarks, returns
- **Types**: name, description, fields, examples, remarks, see also references
- **Annotations**: name, description, examples, remarks

## Usage

\`\`\`typescript
import { pineScriptDocumentation } from './PineScriptContext/enhanced-structures';

// Access variable metadata
const askVar = pineScriptDocumentation.variables.ask;
console.log(askVar.description); // "The ask price at the time..."

// Access function metadata
const alertFunc = pineScriptDocumentation.functions.alert;
console.log(alertFunc.syntax); // "alert(message, freq) → void"
console.log(alertFunc.parameters); // [{ text: "message (series string)..." }]

// Access constant metadata
const colorRed = pineScriptDocumentation.constants.color.red;
console.log(colorRed.description); // "Is a named constant for #F23645 color."
\`\`\`

## Advantages over Manual Structures

1. **Complete metadata**: Includes descriptions, examples, remarks, and cross-references
2. **Always up-to-date**: Regenerated from official documentation
3. **Rich type information**: Full syntax and parameter information for functions
4. **Better IDE support**: Comprehensive JSDoc-style information
5. **Validation**: Can be used for enhanced error messages and autocomplete

## Files

- \`variables.ts\` - All Pine Script variables (160 entries)
- \`functions.ts\` - All Pine Script functions (457 entries)
- \`constants.ts\` - All Pine Script constants (238 entries)
- \`keywords.ts\` - Pine Script keywords (15 entries)
- \`operators.ts\` - Pine Script operators (21 entries)
- \`types.ts\` - Pine Script types (18 entries)
- \`annotations.ts\` - Pine Script annotations (10 entries)
- \`index.ts\` - Main export file

## Regeneration

To regenerate these structures:

\`\`\`bash
npx tsx scripts/generate-enhanced-structures.ts
\`\`\`
`;
}

function main() {
  const jsonlPath = path.join(__dirname, '../PineScriptContext/pinescript_reference.jsonl');
  const outputDir = path.join(__dirname, '../PineScriptContext/enhanced-structures');
  
  console.log('📖 Reading scraped documentation...');
  const content = fs.readFileSync(jsonlPath, 'utf-8');
  const lines = content.trim().split('\n');
  const entries: ScrapedEntry[] = lines.map(line => JSON.parse(line));
  
  console.log(`✅ Loaded ${entries.length} entries`);
  
  // Create output directory
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
    console.log(`📁 Created directory: ${outputDir}`);
  }
  
  // Generate files
  console.log('🔨 Generating TypeScript files...');
  
  const files = [
    { name: 'variables.ts', content: generateVariablesFile(entries) },
    { name: 'functions.ts', content: generateFunctionsFile(entries) },
    { name: 'constants.ts', content: generateConstantsFile(entries) },
    { name: 'keywords.ts', content: generateKeywordsFile(entries) },
    { name: 'operators.ts', content: generateOperatorsFile(entries) },
    { name: 'types.ts', content: generateTypesFile(entries) },
    { name: 'annotations.ts', content: generateAnnotationsFile(entries) },
    { name: 'index.ts', content: generateIndexFile() },
    { name: 'README.md', content: generateReadme() },
  ];
  
  files.forEach(({ name, content }) => {
    const filePath = path.join(outputDir, name);
    fs.writeFileSync(filePath, content);
    console.log(`  ✓ ${name} (${(content.length / 1024).toFixed(1)} KB)`);
  });
  
  // Generate stats
  const stats = {
    variables: entries.filter(e => e.type === 'variable').length,
    functions: entries.filter(e => e.type === 'function').length,
    constants: entries.filter(e => e.type === 'constant').length,
    keywords: entries.filter(e => e.type === 'keyword').length,
    operators: entries.filter(e => e.type === 'operator').length,
    types: entries.filter(e => e.type === 'type').length,
    annotations: entries.filter(e => e.type === 'annotation').length,
  };
  
  console.log('\n📊 GENERATION COMPLETE');
  console.log('─'.repeat(50));
  console.log(`Variables:   ${stats.variables} entries`);
  console.log(`Functions:   ${stats.functions} entries`);
  console.log(`Constants:   ${stats.constants} entries`);
  console.log(`Keywords:    ${stats.keywords} entries`);
  console.log(`Operators:   ${stats.operators} entries`);
  console.log(`Types:       ${stats.types} entries`);
  console.log(`Annotations: ${stats.annotations} entries`);
  console.log(`Total:       ${entries.length} entries`);
  console.log();
  console.log(`📂 Output directory: ${outputDir}`);
}

main();

